### ISSUE TITLE
Ran spladder test errors

### ISSUE THREAD

**Issue by q1134269149** [ratschlab/spladder#101]
* spladder version: 2.3.0 (2.2.2)
* Python version: 3.6 (3.7)
* Operating System: centos servers

### Description

**I want to run spladder test mode after spladder build mode with merge-graphs, the code as following:**
_spladder test -M merge_graphs -a $spladder/A_1.bam,$spladder/A_2.bam,$spladder/A_3.bam  -b $spladder/B_1.bam,$spladder/B_2.bam,$spladder/B_3.bam -c 3 --labelA Wildtype --labelB Mutant --out-tag Round1 -D --plot-format pdf --parallel 8 --outdir $spladder_test_

**but I get some errors, and the log as following:**
>>>
__nohup: ignoring input
/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder_test.py:711: RuntimeWarning: invalid value encountered in less_equal
  k_idx1 = ((sp.mean(cov[0][:, idx1.shape[0]:] <= 1, axis=1) <= options.max_0_frac) | \
/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder_test.py:713: RuntimeWarning: invalid value encountered in less_equal
  k_idx2 = ((sp.mean(cov[1][:, idx1.shape[0]:] <= 1, axis=1) <= options.max_0_frac) | \
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder_test.py", line 161, in estimate_dispersion_chunk
    res = minimize_scalar(likelihood.adj_loglikelihood_scalar, args=(matrix, resp, yhat, sign), method='Bounded', bounds=(0, 10.0), tol=1e-5)
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 781, in minimize_scalar
    return _minimize_scalar_bounded(fun, bounds, args, **options)
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 1800, in _minimize_scalar_bounded
    fu = func(x, *args)
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/testing/likelihood.py", line 62, in adj_loglikelihood_scalar
    raise complexException()
spladder.testing.likelihood.complexException_
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/qinh/anaconda3/envs/spladder2/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder.py", line 188, in main
    options.func(options)
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder_test.py", line 778, in spladder_test
    (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, options, event_type, test_idx)
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder_test.py", line 524, in run_testing
    (disp_raw, disp_raw_conv) = estimate_dispersion(cov, dmatrix1, sf, options, test_idx, event_type)
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/site-packages/spladder/spladder_test.py", line 195, in estimate_dispersion
    tmp = result.pop(0).get()
  File "/home/qinh/anaconda3/envs/spladder2/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
spladder.testing.likelihood.complexException_

<<<
**Can you give me some advice? Thanks!**

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by akahles** [comment]
It seems like that some of the estimates do not converge or you data behaves differently than expected. It might also be a consequence of too few events being available for testing. This is very hard to debug for me without looking at the data at hand.

Would you be able to share a minimal test version, so I can reproduce the crash?
