### ISSUE TITLE
Novel error during spladder test

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#104]
* spladder version:2.3.0
* Python version:3.5
* Operating System:Ubuntu16
* statsmodels version: 1.2.2

### Description

I have processed hg19 chromosome 1 alignments for human samples, and successfully tested each sample against the remaining samples (looking for unique, aberrant splicing). I've now run chromosome 2, and all 'spladder build' steps run .. seemingly correctly. But 'spladder test gives these errors:

```
$ cat sample.err 
/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/spladder/spladder_test.py", line 152, in estimate_dispersion_chunk
    result = modNB.fit()
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1028, in fit
    cov_kwds=cov_kwds, use_t=use_t, **kwargs)
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1166, in _fit_irls
    check_weights=True)
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/statsmodels/regression/_tools.py", line 52, in __init__
    raise ValueError(self.msg.format('endog'))
ValueError: NaN, inf or invalid value detected in endog, estimation infeasible.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/SplAdder/spladder-venv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/spladder/spladder.py", line 188, in main
    options.func(options)
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/spladder/spladder_test.py", line 778, in spladder_test
    (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, options, event_type, test_idx)
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/spladder/spladder_test.py", line 524, in run_testing
    (disp_raw, disp_raw_conv) = estimate_dispersion(cov, dmatrix1, sf, options, test_idx, event_type)
  File "/home/ubuntu/SplAdder/spladder-venv/lib/python3.5/site-packages/spladder/spladder_test.py", line 195, in estimate_dispersion
    tmp = result.pop(0).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
ValueError: NaN, inf or invalid value detected in endog, estimation infeasible.
```

If there's an endog, is there also a begindog?
But seriously ... all samples fail with the same error, and no files are produced in the testing directories. I may try other chromosomes, but right now only chr1 has run test correctly.

**Comment by akahles** [comment]
I think this has been discussed offline. If not and still relevant, please re-open.
Thanks,
Andre

**Comment by lisagrigoreva** [comment]
Hello, have the same issue. Could you please share your discussion here?

**Comment by akahles** [comment]
Dear @lisagrigoreva 
Thanks for reaching out. The discussion was about the specific test setup of the user. Could you please open a new issue describing your setup and then I would try to solve this independently.

Best,

Andre
