### ISSUE TITLE
spladder test error

### ISSUE THREAD

**Issue by rhalperin** [ratschlab/spladder#106]
* spladder version: 2.3.0
* Python version: 3.6.2
* Operating System: CentOS 7

I successfully ran the large cohort workflow on my dataset, and now I am trying to run the differential splicing analysis on the results and I am getting an error.

Here's what I ran:
```
spladder test -o spladder2_out/ -c 3 -a $A -b $B -v -d
```

Here's the error:

```
/packages/spladder/v2.3.0/lib/python3.6/site-packages/numpy-1.17.2-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/packages/spladder/v2.3.0/lib/python3.6/site-packages/numpy-1.17.2-py3.6-linux-x86_64.egg/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Loading expression counts from spladder2_WangKuster/spladder/genes_graph_conf3.merge_graphs.gene_exp.hdf5
Estimating size factors
Testing exon_skip events
Collecting intron confirmation values
Traceback (most recent call last):
  File "/packages/python/3.6.0/lib/python3.6/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: only size-1 arrays can be converted to Python scalars

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/packages/spladder/v2.3.0/bin/spladder", line 11, in <module>
    load_entry_point('spladder==2.3.0', 'console_scripts', 'spladder')()
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/spladder.py", line 188, in main
    options.func(options)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/spladder_test.py", line 682, in spladder_test
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(options.fname_events, idx1_all, idx2_all, event_type, options, gen_event_ids=False, high_mem=options.high_memory)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/alt_splice/quantify.py", line 377, in quantify_from_counted_events
    cnt1.append(IN['event_counts'][strain_idx1, f[0], :][:, conf_idx].T)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/packages/python/3.6.0/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/packages/python/3.6.0/lib/python3.6/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/packages/python/3.6.0/lib/python3.6/site-packages/h5py/_hl/selections.py", line 392, in __getitem__
    mshape = list(count)
UnboundLocalError: local variable 'count' referenced before assignment
```

**Comment by akahles** [comment]
Was addressed in 2.4.2 release.
