### ISSUE TITLE
Spladder test - Hd5f problem: Unable to open file

### ISSUE THREAD

**Issue by raquelgarza** [ratschlab/spladder#107]
* spladder version:2.2.0
* Python version:3.6.5
* Operating System:Linux-gnu

### Description
I want to run spladder test in merge_bams strategy. I have run build with the same strategy and specified the same event-types. 

Spladder build ran without trouble. Spladder test seems to have trouble reading my hdf5 files (I guess..), I get an error saying "unable to open file".

My hdf5 files seem to be ok, if I run: ``` h5ls -r merge_bams_exon_skip_C3.counts.hdf5 ``` I get:
```
/                        Group
/conf_idx                Dataset {18565}
/confirmed               Dataset {53166}
/event_counts            Dataset {8, 7, 53166}
/event_features          Group
/event_features/alt_3prime Dataset {5}
/event_features/alt_5prime Dataset {5}
/event_features/exon_skip Dataset {7}
/event_features/intron_retention Dataset {6}
/event_features/mult_exon_skip Dataset {10}
/event_features/mutex_exons Dataset {9}
/event_pos               Dataset {53166, 6}
/gene_chr                Dataset {58870}
/gene_idx                Dataset {53166}
/gene_names              Dataset {58870}
/gene_pos                Dataset {58870, 2}
/gene_strand             Dataset {58870}
/iso1                    Dataset {8, 53166}
/iso2                    Dataset {8, 53166}
/num_verified            Dataset {53166, 4}
/psi                     Dataset {8, 53166}
/strains                 Dataset {8}
/verified                Dataset {53166, 8, 4}

```
Which seems ok to me (similar thing with all hdf5 files)...

g1_g2_bams.txt contains the full path to all the bam files. G1_bams.txt to the bams of the group 1, g2_bams.txt to the ones of the group 2.

Here is my code:

### What I Did

```
spladder build --bams g1_g2_bams.txt -o ../4_spladder/g1_vs_g2/ -a annotation.gtf --merge-strat merge_bams --event-types exon_skip,mutex_exons,intron_retention,mult_exon_skip

spladder test --conditionA g1_bams.txt --conditionB g2_bams.txt --labelA g1 --labelB g2 --merge-strat merge_bams --outdir ../4_spladder/g1_vs_g2/ --diagnose-plots --plot-format pdf --event-types exon_skip,mutex_exons,intron_retention,mult_exon_skip

Traceback (most recent call last):
  File "/sw/pkg/spladder/v2.2.0/envs/spladderenv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/sw/pkg/spladder/v2.2.0/envs/spladderenv/lib/python3.6/site-packages/spladder/spladder.py", line 182, in main
    options.func(options)
  File "/sw/pkg/spladder/v2.2.0/envs/spladderenv/lib/python3.6/site-packages/spladder/spladder_test.py", line 668, in spladder_test
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(options.fname_events, idx1_all, idx2_all, event_type, options, gen_event_ids=False, low_mem=options.low_memory)
  File "/sw/pkg/spladder/v2.2.0/envs/spladderenv/lib/python3.6/site-packages/spladder/alt_splice/quantify.py", line 279, in quantify_from_counted_events
    IN = h5py.File(event_fn, 'r', driver='core', backing_store=False)
  File "/sw/pkg/spladder/v2.2.0/envs/spladderenv/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/sw/pkg/spladder/v2.2.0/envs/spladderenv/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file)

```

Any help would be greatly appreciated!

/Raquel

**Comment by akahles** [comment]
Sorry for never replying to this. Although it is likely too late now, my advice would be to run the testing for a single event_type at a time, using the latest release version. 

If the issue is still relevant on the latest version, please re-open.

Best,
Andre
