### ISSUE TITLE
an error in detect.py.

### ISSUE THREAD

**Issue by mhjiang97** [ratschlab/spladder#109]
* spladder version: 2.4.2
* Python version: 3.7.4
* Operating System: Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018

### Description
I tried to call as event in the end, as I have finished the previous steps successfully according to your "large cohort advise". I have these files in my output directory(I put 4 bams into spladder):
```
genes_graph_conf2.merge_graphs.count.hdf5                       genes_graph_conf2.merge_graphs.pickle
genes_graph_conf2.merge_graphs.PANATY.sortedByCoord.count.hdf5  genes_graph_conf2.PANATY.sortedByCoord.pickle
genes_graph_conf2.merge_graphs.PANDBX.sortedByCoord.count.hdf5  genes_graph_conf2.PANDBX.sortedByCoord.pickle
genes_graph_conf2.merge_graphs.PANLGK.sortedByCoord.count.hdf5  genes_graph_conf2.PANLGK.sortedByCoord.pickle
genes_graph_conf2.merge_graphs.PANSBK.sortedByCoord.count.hdf5  genes_graph_conf2.PANSBK.sortedByCoord.pickle
```

However, there was a crash in the last step.
### What I Did
the code I run:
```
spladder build -o ~/projects/bcpall/analysis/rnaseq/as/SJBALL020700_spladder \
-a ${gtf} \
-b ${bam_dir}/PANATY/PANATY.sortedByCoord.bam,${bam_dir}/PANDBX/PANDBX.sortedByCoord.bam,${bam_dir}/PANLGK/PANLGK.sortedByCoord.bam,${bam_dir}/PANSBK/PANSBK.sortedByCoord.bam \
-n 50 \
-c 2 \
--set-mm-tag nM \
--ase-edge-limit 300 \
--event-types exon_skip,intron_retention,alt_3prime,alt_5prime,mult_exon_skip,mutex_exons
```
the error:
```
Traceback (most recent call last):
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/lib/python3.7/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/lib/python3.7/site-packages/spladder/spladder_build.py", line 252, in spladder
    collect_events(options)
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/lib/python3.7/site-packages/spladder/alt_splice/collect.py", line 76, in collect_events
    idx_intron_reten, intron_intron_reten = detect_events(genes, 'intron_retention', sp.where([x.is_alt for x in genes])[0], options)
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/lib/python3.7/site-packages/spladder/alt_splice/detect.py", line 416, in detect_events
    result_list = detect_wrapper(genes[idx], event_type, idx, None, edge_limit=options.detect_edge_limit, log=options.verbose)[0]
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/lib/python3.7/site-packages/spladder/alt_splice/detect.py", line 373, in detect_wrapper
    return (detect_intronreten(genes, gidx, log, edge_limit), idx)
  File "/lustre/home/acct-medhjy/medhjy-s3/.conda/envs/test/lib/python3.7/site-packages/spladder/alt_splice/detect.py", line 128, in detect_intronreten
    if edges.shape[0] > edge_limit:
TypeError: '>' not supported between instances of 'int' and 'str'
```
Could you please tell me why this error occurred  and how to fix it?
I'm looking forward to your reply!~Thank you very much!

**Comment by akahles** [comment]
This has been fixed with the latest release. Please re-open the issue if you find otherwise.
