### ISSUE TITLE
Installation error with pip install and git clone

### ISSUE THREAD

**Issue by JamalEH** [ratschlab/spladder#111]
* spladder version: spladder==2.4.2 (latest version) 
* Python version: 3.7
* Operating System: fedora version 28

### Description

While trying to install spladder 2.4.2 through pip install pip install spladder or git clone https://github.com/ratschlab/spladder.git, the installation finishes without problem.

but when runing the spladder command I go the following error:
 spladder

Traceback (most recent call last):
  File "__init__.pxd", line 1036, in numpy.import_array
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jelhasnaoui/anaconda/bin/spladder", line 11, in <module>
    load_entry_point('spladder==2.4.2', 'console_scripts', 'spladder')()
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/spladder-2.4.2-py3.6.egg/spladder/spladder.py", line 10, in <module>
    from .spladder_test import spladder_test
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/spladder-2.4.2-py3.6.egg/spladder/spladder_test.py", line 3, in <module>
    import statsmodels.api as sm
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/api.py", line 11, in <module>
    from .regression.recursive_ls import RecursiveLS
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/regression/recursive_ls.py", line 14, in <module>
    from statsmodels.tsa.statespace.mlemodel import (
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 32, in <module>
    from .simulation_smoother import SimulationSmoother
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/tsa/statespace/simulation_smoother.py", line 9, in <module>
    from .kalman_smoother import KalmanSmoother
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/tsa/statespace/kalman_smoother.py", line 10, in <module>
    from statsmodels.tsa.statespace.representation import OptionWrapper
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/tsa/statespace/representation.py", line 9, in <module>
    from .tools import (
  File "/home/jelhasnaoui/anaconda/lib/python3.6/site-packages/statsmodels/tsa/statespace/tools.py", line 14, in <module>
    from . import (_initialization, _representation, _kalman_filter,
  File "statsmodels/tsa/statespace/_representation.pxd", line 13, in init statsmodels.tsa.statespace._initialization
  File "statsmodels/tsa/statespace/_representation.pyx", line 1, in init statsmodels.tsa.statespace._representation
  File "statsmodels/tsa/statespace/_tools.pyx", line 16, in init statsmodels.tsa.statespace._tools
  File "__init__.pxd", line 1038, in numpy.import_array

What may be the problem ?

Thank you in advance!
Kind regards,
Jamal.

**Comment by JamalEH** [comment]
Problem solved.

It was due to an older version of numpy installed. Upgrading numpy to later version solved the issue.

Best regards,
Jamal.
