### ISSUE TITLE
Running spladder viz mode

### ISSUE THREAD

**Issue by jjyotikataria** [ratschlab/spladder#114]
* spladder version:
* Python version:3.6
* Operating System:
  Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)

### Description

I tried to run spladder viz command

### What I Did

/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/bin/spladder viz -o . --track event intron_retention -c 2

Output: 

/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_viz.py", line 237, in spladder_viz
    _parse_event_info(eids, gids, range_info[1:], events, options.outdir, options.confidence, options.verbose)
  File "/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_viz.py", line 69, in _parse_event_info
    events.extend(load_events(sp.array(id_array), outdir, confidence, verbose))
  File "/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/lib/python3.6/site-packages/spladder/helpers_viz.py", line 82, in load_events
    for event_type in sp.unique(event_info[:, 0]):
IndexError: too many indices for array

**Comment by akahles** [comment]
It seems that no intron retention event was found and hence none can be plotted. I will have add to my todo list to generate a more meaningful error message here.

**Comment by jjyotikataria** [comment]
Also, I tried for all the events one by one in this command, its always showing this error:
IndexError: too many indices for array


I checked the log file, no event is found in the file, I guess thats the reason.

No exon_skip event could be confirmed. - Nothing to report.
No intron_retention event could be confirmed. - Nothing to report.
No alt_3prime event could be confirmed. - Nothing to report.
No alt_5prime event could be confirmed. - Nothing to report.
No mutex_exons event could be confirmed. - Nothing to report.
No mult_exon_skip event could be confirmed. - Nothing to report.

**Comment by monahash** [comment]
Hi, 
I have the same error even though I have exon skipping and intron retention events reported from the build mode in txt and gff3 files. Also, these events have been verified by other tools, but I wanted to use the viz mode for the plot. 

The output files of the build mode:
merge_graphs_intron_retention_C3.confirmed.txt.gz
merge_graphs_intron_retention_C3.confirmed.gff3
merge_graphs_intron_retention_C3.confirmed.pickle
merge_graphs_intron_retention_C3.counts.hdf5
merge_graphs_exon_skip_C3.confirmed.txt.gz
merge_graphs_exon_skip_C3.confirmed.gff3
merge_graphs_exon_skip_C3.confirmed.pickle
merge_graphs_exon_skip_C3.counts.hdf5
merge_graphs_exon_skip_C3.pickle
merge_graphs_intron_retention_C3.pickle
genes_graph_conf3.merge_graphs.names.pickle
genes_graph_conf3.merge_graphs.count.hdf5.quick_edge_idx
genes_graph_conf3.merge_graphs.count.hdf5.quick_ids_edges
genes_graph_conf3.merge_graphs.count.hdf5.quick_ids_segs
genes_graph_conf3.merge_graphs.count.hdf5
genes_graph_conf3.merge_graphs.pickle
genes_graph_conf3.accepted_hits.dedup.pickle
genes_graph_conf0.merge_graphs.names.pickle
genes_graph_conf0.merge_graphs.count.hdf5.quick_edge_idx
genes_graph_conf0.merge_graphs.count.hdf5.quick_ids_edges
genes_graph_conf0.merge_graphs.count.hdf5.quick_ids_segs
genes_graph_conf0.merge_graphs.count.hdf5
genes_graph_conf0.merge_graphs.pickle
genes_graph_conf0.accepted_hits.dedup.pickle


Running viz mode:
spladder viz --range gene gene1 -o . \
--track coverage,segments /Directory/to/Mysample.bam \
--track splicegraph \
--track event exon_skip \
 --outbase gene1_test \
--format pdf

The error 
  File "/software/conda_envs/spladder/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/software/conda_envs/spladder/lib/python3.7/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/software/conda_envs/spladder/lib/python3.7/site-packages/spladder/spladder_viz.py", line 237, in spladder_viz
    _parse_event_info(eids, gids, range_info[1:], events, options.outdir, options.confidence, options.verbose)
  File "/software/conda_envs/spladder/lib/python3.7/site-packages/spladder/spladder_viz.py", line 69, in _parse_event_info
    events.extend(load_events(sp.array(id_array), outdir, confidence, verbose))
  File "/software/conda_envs/spladder/lib/python3.7/site-packages/spladder/helpers_viz.py", line 82, in load_events
    for event_type in sp.unique(event_info[:, 0]):
IndexError: too many indices for array
