### ISSUE TITLE
Running viz mode with all events

### ISSUE THREAD

**Issue by jjyotikataria** [ratschlab/spladder#115]
* spladder version:
*Python version:3.6.4
*Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.2:GA:server

### Description

I tried to run viz command for gene1 with all the event types, I got the following error

### What I Did

/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/bin/spladder viz -o . --range gene GENE1 --track event any --track splicegraph --track transcript --track coverage /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/conf3_2bam/CHECK/EXAMPLE/data/align/pos_1.bam /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/conf3_2bam/CHECK/EXAMPLE/data/align/pos_2.bam /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/conf3_2bam/CHECK/EXAMPLE/data/align/pos_3.bam /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/conf3_2bam/CHECK/EXAMPLE/data/align/pos_3.bam /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/conf3_2bam/CHECK/EXAMPLE/data/align/pos_4.bam /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/conf3_2bam/CHECK/EXAMPLE/data/align/pos_5.bam -O mytest  -f pdf

Error:

Traceback (most recent call last):
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_viz.py", line 337, in spladder_viz
    label=label))
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/viz/coverage.py", line 237, in cov_from_bam
    (counts, intron_counts, intron_list) = _get_counts(chr_name, start, stop, files, intron_cov, intron_cnt, verbose, collapsed=True)
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/viz/coverage.py", line 47, in _get_counts
    for line in infile.fetch(chr_name, start, stop):
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 692, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-6)

Can you help me whats going wrong?

**Comment by akahles** [comment]
Thanks for pointing this out. There was a bug in selecting the plotting range which came to light when you used the very tiny example data. I have implemented a fix, which is now available in the development branch. I we make it available as a new release in the next days.
