### ISSUE TITLE
Running test mode for all the events

### ISSUE THREAD

**Issue by jjyotikataria** [ratschlab/spladder#118]
* spladder version:2.4.2
* Python version: 3.6.4
* Operating System: centOS

### Description

I tried running test mode for all the events, the manual says be default it runs for every event.

I used this command:

/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/bin/spladder test -o . -v --diagnose-plots -f pdf --merge-strat merge_graphs --readlen 50 -a bam1.txt -b bam2.txt

Before that, I ran build as joint analysis for all 4 bam files and then kept two two in bam1 and bam2.txt for test command.

/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/bin/spladder build -o . -a /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/EXAMPLE/spladder-master/tests/testcase_events/data/testcase_events_spladder.gtf -b bam.txt  --extract-ase --event-types exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip --readlen 15 --output-conf-icgc --output-txt --output-txt-conf --output-gff3 --output-struc --output-struc-conf --output-bed --output-conf-bed --output-conf-tcga --parallel 30 --merge-strat merge_graphs

```What does this error mean? What to do now?
Error:

/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_test.py:238: RuntimeWarning: invalid value encountered in greater
  idx = sp.where((disp_raw > lowerBound) & (disp_raw < upperBound))[0]
/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_test.py:238: RuntimeWarning: invalid value encountered in less
  idx = sp.where((disp_raw > lowerBound) & (disp_raw < upperBound))[0]
/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py:774: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum(resid / self.family.variance(mu)) / self.df_resid
Traceback (most recent call last):
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_test.py", line 778, in spladder_test
    (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, options, event_type, test_idx)
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_test.py", line 527, in run_testing
    (disp_fitted, Lambda, disp_idx) = fit_dispersion(cov, disp_raw, (disp_raw_conv[:, 0] & test_idx)[:, sp.newaxis], sf, options, dmatrix1, event_type)
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/spladder/spladder_test.py", line 246, in fit_dispersion
    res = modGamma.fit()
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1027, in fit
    cov_kwds=cov_kwds, use_t=use_t, **kwargs)
  File "/home/nitin.m/SPLAADER/spladder-master/Python-3.6.4/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1142, in _fit_irls
    raise ValueError("The first guess on the deviance function "
ValueError: The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.

**Comment by akahles** [comment]
As per our communication per e-mail. You are trying to run SplAdder on the small test-case data that comes with the code to test for correctness. This data will not work for running a differential test. I will add to the todo list to provide a larger example data set where these things can be tried out.

Cheers,
Andre
