### ISSUE TITLE
Spladder build: Unable to open Hdf5 file

### ISSUE THREAD

**Issue by apuhegde** [ratschlab/spladder#121]
* spladder version: 2.3.0
* Python version: 3.6.0
* Operating System:CentOS Linux 7

I'm trying to run spladder on some samples, starting from bam files. Some samples pass the first step fine (spladder build), but for other samples, I get the error below. This error is repeated on the same set of samples when I try to run using spladder v2.2.3.

The command I ran was:
```
module load spladder/v2.3.0

spladder build -o outDir -a reference.gtf -b bam_path.bam -n 101 --validate-sg  -c 2 --sparse-bam  --merge-strat single --no-extract-ase
```

The output for the failed samples was:

```
Augmenting splice graphs.
=========================
Generating splice graph ...
...done.

Loading introns from file ...
Traceback (most recent call last):
  File "/packages/spladder/v2.3.0/bin/spladder", line 11, in <module>
    load_entry_point('spladder==2.3.0', 'console_scripts', 'spladder')()
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/spladder.py", line 188, in main
    options.func(options)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/spladder_build.py", line 152, in spladder
    spladder_core(options)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, options)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/core/gen_graphs.py", line 81, in gen_graphs
    introns = get_intron_list(genes, options)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/reads.py", line 406, in get_intron_list
    (regions, options) = init_regions(options.bam_fnames, options.confidence, options, sparse_bam=options.sparse_bam)
  File "/packages/spladder/v2.3.0/lib/python3.6/site-packages/spladder-2.3.0-py3.6.egg/spladder/init.py", line 316, in init_regions
    IN = h5py.File(re.sub(r'.bam$', '', fn_bams[i]) + '.conf_%i' % conf + '.filt.hdf5', 'r')
  File "/packages/python/3.6.0/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/packages/python/3.6.0/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)

```

I'd appreciate your help with debugging this. Strange thing is that the same set of samples give this problem every time, other samples run fine. I have not tried using Spladder v2.4.2 yet.
Thanks!

**Comment by akahles** [comment]
There was a bug in filename/sample name matching which should be resolved with the upcoming release. If your problem still persists afterwards, please report here.
