### ISSUE TITLE
failure at viz mode with --range coordinate 

### ISSUE THREAD

**Issue by nongbaoting** [ratschlab/spladder#129]
* spladder version: 2.4.2
* Python version: 3.7
* Operating System: ubuntu 18.04

### Description

I ran spladder with viz mode, all is right except with `--range coordinate `

# CMD

```
spladder viz  --range coordinate chr3 100807161 100847446 \
--track coverage tumor:../star2pass/ad80db19-db47-4288-8c78-87de24f267e4_gdc_realn_rehead.bam,../star2pass/386ab3b5-5a37-47ce-b525-d717cf5c30a6_gdc_realn_rehead.bam \
--track coverage adjacent_tumor:../star2pass/40ce52ae-fba8-4947-b35e-cebbc8b36480_gdc_realn_rehead.bam,../star2pass/a4d6af35-c7cc-4281-9c0f-5c2e795a5e7a_gdc_realn_rehead.bam  \
--track event mult_exon_skip.5454  \
-o ../spladder_out/spladder_out/  \
-O THCA_event 
```

# error!
```
Traceback (most recent call last):
  File "/home/nbt2/miniconda3/envs/AS/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/home/nbt2/miniconda3/envs/AS/lib/python3.7/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/home/nbt2/miniconda3/envs/AS/lib/python3.7/site-packages/spladder/spladder_viz.py", line 244, in spladder_viz
    plotchrm = sp.unique([_.chr for _ in sp.r_[events, genes, coords]])
  File "/home/nbt2/miniconda3/envs/AS/lib/python3.7/site-packages/numpy/lib/index_tricks.py", line 406, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)
```

**Comment by akahles** [comment]
Dear @nongbaoting ,

Thank you very much for reporting this. The issue should be fixed in the current master and development branches. Please let me know if the issue still persists.

Thanks,

Andre

**Comment by akahles** [comment]
Please re-open in case this is still an issue.
