### ISSUE TITLE
h5py.file or os.path.join is forcing lowercase and causing error in spladder_viz.py

### ISSUE THREAD

**Issue by warrenmcg** [ratschlab/spladder#14]
Hi,

I wanted to visualize some of the results I got from running SplAdder and rDiff, and I got the following error:
```
IOError: Unable to open file (Unable to open file: name = 'spladder_results3/merge_graphs_alt_5primer_c3.counts.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
spladder_results3/
Traceback (most recent call last):
  File "/home/warren/Downloads/spladder_devel/spladder/python/spladder_viz.py", line 244, in <module>
    spladder_viz()
  File "/home/warren/Downloads/spladder_devel/spladder/python/spladder_viz.py", line 176, in spladder_viz
    event_info = get_conf_events(options, gid)
  File "/home/warren/Downloads/spladder_devel/spladder/python/modules/identity.py", line 60, in get_conf_events
    IN = h5py.File(os.path.join(options.outdir, 'merge_graphs_%s_C%i.counts.hdf5' % (event_type, options.confidence)), 'r')
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-WAOaVj/h5py/h5py/_objects.c:2574)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-WAOaVj/h5py/h5py/_objects.c:2533)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-build-WAOaVj/h5py/h5py/h5f.c:1811)
```

Taking a look at the first line, it appears that somewhere along the way, the file name "spladder_results3/merge_graphs_alt_5primer_C3.counts.hdf5" got changed to "spladder_results3/merge_graphs_alt_5primer_c3.counts.hdf5", with the C forced to lower case. I'm not sure how to solve this other than renaming the files to lower-case, but wanted to bring this to your attention.

**Comment by warrenmcg** [comment]
Oops, I just realized that I put in a typo that was looking for "alt_5primer" rather than "alt_5prime" for the alternative splicing event. I don't know why this forced everything to lowercase, but fixing this typo solved the problem. Maybe there can be a way to check that AS events included with the `-t` flag are correct?
