### ISSUE TITLE
Spladder Testing issue

### ISSUE THREAD

**Issue by OnkarMulay** [ratschlab/spladder#142]
spladder version: 2.4.4
Python version: 3.8.5
Operating System: Unix
The build mode of the spladder was successful, it seems so. But have issues for test mode.

## Output file
Reporting complete exon_skip events:

Reporting confirmed exon_skip events:
writing exon_skip events in gff3 format to /scratch/zq45/om4416/Spladder_Eva_train/merge_graphs_exon_skip_C3.confirmed.gff3
writing exon_skip events in flat txt format to /scratch/zq45/om4416/Spladder_Eva_train/merge_graphs_exon_skip_C3.confirmed.txt.gz

Capped 15788/6183648 outlier expression counts (0.26 percent)

Found dispersion fit

## CODE
#!/bin/tcsh
#PBS -l walltime=30:00:00
#PBS -q normal
#PBS -l jobfs=1gb
#PBS -l mem=64gb
#PBS -l ncpus=48
#PBS -P zq45

conda activate /miniconda3/envs/Spladder

spladder build --bams /Spladder_bam.txt --annotation /Homo_sapiens.GRCh38.100.chr.gtf --merge-strat merge_graph**s** --quantify-graph --qmode all --ignore-mismatches --outdir /Spladder_Eva_train

spladder test --conditionA /Eva_Spladder_bam1.txt --conditionB /Eva_Spladder_bam2.txt --outdir /Spladder_Eva_train

## Error
Traceback (most recent call last):
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/spladder_build.py", line 259, in spladder
    analyze_events(options, options.event_types[e_idx])
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/alt_splice/analyze.py", line 296, in analyze_events
    write_events_txt(fn_out_conf_txt, options.strains[sample_idx], events_all, fn_out_count, event_idx=confirmed_idx)
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/alt_splice/write.py", line 90, in write_events_txt
    counts = event_counts_chunk[:, :, i - chunk_idx_event[0]]
IndexError: index 2901 is out of bounds for axis 2 with size 1725
Traceback (most recent call last):
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/spladder_test.py", line 675, in spladder_test
    with h5py.File(options.fname_events, 'r') as IN:
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/scratch/zq45/om4416/Spladder_Eva_train/merge_graphs_intron_retention_C3.counts.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by akahles** [comment]
Dear @OnkarMulay ,

Sorry for the late reply. The error messages you report seem to be from two independent calls to SplAdder - one from `build` mode and one from `test` mode. For the testing, it is likely, that no events of the desired type were found. You can try to run SplAdder only on exon skips, using the option `--event_types exon_skip`. 

I will go over the testing mode again and make sure that an appropriate error is reported if no events were found.

Best,

Andre

**Comment by phoebemma** [comment]
I am currently having same issue (or perhaps similar). I had to also update to the latest version and the same error keeps occuring during testing. Find error message below

File "/home/chidimma/.conda/envs/Trainome_pipe/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/spladder/spladder_test.py", line 552, in spladder_test
    gene_counts, gene_samples, gene_sample_idx, gene_ids, gene_symbols = _get_gene_expression(options, options.fname_exp_hdf5, sample_subset=condition_samples)
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/spladder/spladder_test.py", line 33, in _get_gene_expression
    IN = h5py.File(fname_exp_hdf5, 'r')
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/datastore/Chidimma/Trainome_data/Phase_1_analyses/COPD_dataset/SplAdder_workspace/Sample_105_106_110_113/1SplAdder/spladder/genes_graph_conf2.merge-graphs.gene_exp.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by phoebemma** [comment]
Hello Andre, 
I guess I can give a response on this thread. Below are the commands I used. I actually used underscore

ls -1 $input > bamfiles.txt

spladder build -o $output_dir -a $annotated_dir -b bamfiles.txt --merge-strat single --no-extract-ase --sparse-bam --parallel 24 --confidence 2 --output-txt


spladder build -o $output_dir -a $annotated_dir -b bamfiles.txt --merge-strat merge_graphs --no-extract-ase --sparse-bam --parallel 24 --confidence 2 --output-txt --quantify-graph

for file in $input
do
spladder build -o $output_dir -b $file -a $annotated_dir --merge-strat merge_graphs --no-extract-ase --quantify-graph --qmode single --confidence 2 --parallel 24
done 

spladder build -o $output_dir -a $annotated_dir -b bamfiles.txt --merge-strat merge_graphs --no-extract-ase --sparse-bam --parallel 24 --confidence 2 --output-txt --quantify-graph --qmode collect

spladder build -o $output_dir -a $annotated_dir -b bamfiles.txt --merge-strat merge_graphs --ase-edge-limit 1500 --sparse-bam --parallel 24 --confidence 2 --output-txt --no-compress-text

**Comment by akahles** [comment]
Hi Chidimma,

The file names in SplAdder are automatically constructed from the given parameters. Given your error message, the file that is being looked for is:

/datastore/Chidimma/Trainome_data/Phase_1_analyses/COPD_dataset/SplAdder_workspace/Sample_105_106_110_113/1SplAdder/spladder/genes_graph_conf2.merge-graphs.gene_exp.hdf5

So somewhere in the inputs there was a `merge-graphs` instead of a `merge_graphs`. Just for due diligence, I scanned the SplAdder codebase. It does not contain any occurrence of merge-graphs. 

Would you mind re-running your pipeline with the below commands (which look good to me) and check whether the error still persists?

Best,

Andre

**Comment by phoebemma** [comment]
Hello Andre,
Thanks for your response. I have just seen that I used merge-graph in my the spladder  test commands. I am repeating the analyses again. Would provide feedback when this is completed.
Regards, 
Chidimma

**Comment by phoebemma** [comment]
I got a different kind of error this time

/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/numpy/core/_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
Traceback (most recent call last):
  File "/home/chidimma/.conda/envs/Trainome_pipe/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/spladder/spladder_test.py", line 597, in spladder_test
    (cov, psi, gene_idx, event_idx, event_ids, event_samples) = quantify.quantify_from_counted_events(options.fname_event_counts, idx1, idx2, event_type, options, gen_event_ids=False, high_mem=options.high_memory)
  File "/home/chidimma/.conda/envs/Trainome_pipe/lib/python3.9/site-packages/spladder/alt_splice/quantify.py", line 401, in quantify_from_counted_events
    if samples[0].endswith('npz'):
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by phoebemma** [comment]
Hello Andre!
I have it solved. It apparently had something to do with how "ls-1" listed the file paths. I fixed that and the test is running as expected. Thanks for your help
