### ISSUE TITLE
Passing NoneType to string formatting operand

### ISSUE THREAD

**Issue by shepp-hub** [ratschlab/spladder#147]
* spladder version: 2.4.4
* Python version: 3.7
* Operating System: CentOS 7
### Description

While running spladder build, I had this little warning message pop up and crash.
It's just a tiny issue that could be fixed by either accounting for `strand is None`, or maybe not printing it at all.
It's a tiny, easy to fix issue, but it might be intimidating for programming-averse users.

### What I Did

```
Traceback (most recent call last):
  File "/groups/nshomron/guyshapira/.local/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/groups/nshomron/guyshapira/.local/lib/python3.7/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/groups/nshomron/guyshapira/.local/lib/python3.7/site-packages/spladder/spladder_build.py", line 83, in spladder
    (genes, options) = init.init_genes_gff3(options)
  File "/groups/nshomron/guyshapira/.local/lib/python3.7/site-packages/spladder/init.py", line 218, in init_genes_gff3
    genes[tags['ID']] = Gene(name=tags['ID'], start=start, stop=stop, chr=sl[0], strand=sl[6], source=sl[1], gene_type=sl[2])
  File "/groups/nshomron/guyshapira/.local/lib/python3.7/site-packages/spladder/classes/gene.py", line 23, in __init__
    warnings.warn('WARNING: strand of gene was provided as %s - automatically set to +') % strand
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'
```

**Comment by akahles** [comment]
Dear @shepp-hub ,

Thank you very much for reporting. I have fixed the issue in the `development` branch. The change will be available with the next release.

Best,

Andre

**Comment by akahles** [comment]
Closing this, please re-open if still relevant.
