### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by illarionovaanastasia** [ratschlab/spladder#148]
* spladder version: 3.0.0
* Python version: 3.9
* Operating System: linux-64

### Description

Hi! I have tried to run the build mode on the short read RNA-seq bam files. Spladder has crashed with an attribute error.

### What I Did
```
for f in bams/*.bam
do
    spladder build -a gencode_v29.lncipedia_v5_2_hc.annotation.sorted.gtf -o spladder_out -b $f \
                   --merge-strat merge_graphs \
                   --no-extract-ase \
                   --quantify-graph \
                   --qmode single --ignore-mismatches
done
```

```
Inserting new intron edges ...
... chr GL000009.2 - iteration 1/5

... removing duplicate exons ...
Traceback (most recent call last):
  File "/home/miniconda3/bin/spladder", line 33, in <module>
    sys.exit(load_entry_point('spladder==3.0.0', 'console_scripts', 'spladder')())
  File "/home/miniconda3/lib/python3.9/site-packages/spladder-3.0.0-py3.9.egg/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/home/miniconda3/lib/python3.9/site-packages/spladder-3.0.0-py3.9.egg/spladder/spladder_build.py", line 80, in spladder
    spladder_core(options.bam_fnames[idx], out_fname, options)
  File "/home/miniconda3/lib/python3.9/site-packages/spladder-3.0.0-py3.9.egg/spladder/core/spladdercore.py", line 23, in spladder_core
    genes = gen_graphs(genes, bam_fnames, options)
  File "/home/miniconda3/lib/python3.9/site-packages/spladder-3.0.0-py3.9.egg/spladder/core/gen_graphs.py", line 180, in gen_graphs
    _updated = np.where([genes_mod[i] != genes_before[i] for i in range(len(genes_mod))])[0].shape[0]
  File "/home/miniconda3/lib/python3.9/site-packages/spladder-3.0.0-py3.9.egg/spladder/core/gen_graphs.py", line 180, in <listcomp>
    _updated = np.where([genes_mod[i] != genes_before[i] for i in range(len(genes_mod))])[0].shape[0]
  File "/home/miniconda3/lib/python3.9/site-packages/spladder-3.0.0-py3.9.egg/spladder/classes/gene.py", line 51, in __eq__
    (self.symbol == other.symbol)
AttributeError: 'Gene' object has no attribute 'symbol'
```
Thank you for your help in advance!

Anastasia

**Comment by akahles** [comment]
Dear Anastasia,

Thanks for trying out SplAdder. This issue relates to a new feature that allows to carry through gene names from the annotation. Are you running SplAdder on an annotation file that you have previously used? If so, could you remove the `<annotation_file>.pickle` file and re-run?

Thanks and Cheers,
Andre

**Comment by illarionovaanastasia** [comment]
Dear Andre,

I have removed <annotation_file>.pickle file, and the run went successfully. 
Thank you!

Best regards,
Anastasia

**Comment by akahles** [comment]
Dear Anastasia,

Thank you very much for reporting back. I will close this issue for now. Please open a new one in case you encounter any other difficulties.

Best,

Andre
