### ISSUE TITLE
AttributeError: 'Gene' object has no attribute 'symbol'

### ISSUE THREAD

**Issue by wir963** [ratschlab/spladder#150]
* spladder version: 3.0.0
* Python version: 3.10.2
* Operating System: Linux

### Description

Hey Andre,

I'm getting the below bug upon updating to 3.0.0. I am using the exact set of commands that worked for version 2.4.4 taken from [running on large cohorts](https://spladder.readthedocs.io/en/latest/spladder_cohort.html) adapted to using conda and snakemake. This failed on the first step. 

### What I Did

```
spladder build --bams <bam_file> --annotation <gtf_file> --outdir output/individual_splicing_graphs --tmp-dir /lscratch/$SLURM_JOB_ID --set-mm-tag nM --verbose --merge-strat single --parallel 4 --no-extract-ase

Traceback (most recent call last):
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/bin/spladder", line 8, 
in <module>
    sys.exit(main())
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-pac
kages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-pac
kages/spladder/spladder_build.py", line 80, in spladder
    spladder_core(options.bam_fnames[idx], out_fname, options)
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/core/spladdercore.py", line 23, in spladder_core
    genes = gen_graphs(genes, bam_fnames, options)
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/core/gen_graphs.py", line 180, in gen_graphs
    _updated = np.where([genes_mod[i] != genes_before[i] for i in range(len(genes_mod))])[0].shape[0]
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/core/gen_graphs.py", line 180, in <listcomp>
    _updated = np.where([genes_mod[i] != genes_before[i] for i in range(len(genes_mod))])[0].shape[0]
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/classes/gene.py", line 51, in __eq__
    (self.symbol == other.symbol)
AttributeError: 'Gene' object has no attribute 'symbol'
```

Best, Welles

**Comment by akahles** [comment]
Hi Welles,

if you have run a 2.x SplAdder version on the same annotation before. Can you please remove the `<annotation>.pickle` file, if your annotation is called `<annotation>`? SplAdder should re-parse it and add the required symbols.

Best,

Andre

**Comment by wir963** [comment]
Hey Andre, 

I am using the same annotation as before and there was indeed an `<annotation>.pickle` file. I've deleted that file and kicked off the jobs. I'm still waiting for the job to finish but it's made it past where it failed yesterday so I'll go ahead and close out the issue. Thanks again for your help. 

Best, Welles
