### ISSUE TITLE
NameError: name 'get_filename' is not defined

### ISSUE THREAD

**Issue by wir963** [ratschlab/spladder#151]
* spladder version: 3.0.0
* Python version: 3.10.2
* Operating System: Linux

### Description

Hey Andre, 

I am trying to collect the individual quantifications and aggregate them into a joint database [as described here](https://spladder.readthedocs.io/en/latest/spladder_cohort.html#quantification).

### What I Did

```
spladder build --bams data/4391_cohort.txt --annotation /data/CCRSB/lib/GTF_files/Homo_sapiens_Ensembl_GRCh37.gtf --outdir output/4391 --tmp-dir /lscratch/$SLURM_JOB_ID --set-mm-tag nM --verbose --merge-strat merge_graphs --parallel 4 --no-extract-ase --quantify-graph --qmode collect 

Collecting count data from files quantified in single mode ...

writing data to output/4391/spladder/genes_graph_conf3.merge_graphs.count.hdf5
Traceback (most recent call last):
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/spladder_build.py", line 138, in spladder
    collect_single_quantification_results(fn_out_count, idxs, options)
  File "/gpfs/gsfs9/users/Robinson-SB/SplAdder/.snakemake/conda/a04ed9344772bbdc0596fc821ba47599/lib/python3.10/site-packages/spladder/count.py", line 193, in collect_single_quantification_results
    fname = get_filename('fn_collect_in', options, options.samples[idx])
NameError: name 'get_filename' is not defined
```

Best, Welles

**Comment by akahles** [comment]
Dear Welles,

Thanks a lot for reporting. Somehow the import got lost. I have fixed it and will release a new version shortly.

Cheers,

Andre

**Comment by akahles** [comment]
This should be fixed in the latest release. Please re-open, if you find otherwise.

Cheers,

Andre

**Comment by wir963** [comment]
Hey Andre, 

Thanks for the fix. Can confirm it is now running on my data.

Best, Welles
