### ISSUE TITLE
IndexError during spladder test intron_retension

### ISSUE THREAD

**Issue by paulojannig** [ratschlab/spladder#152]
* spladder version: 3.0.1
* Python version: 3.10.2
* Operating System: Ubuntu 20.04.3 LTS

### Description

Hi again Andre!

Now I'm having an issue during `spladder test`. I'm getting `IndexError` only for `--event-types intron_retension`, so test_results are not generated for intron_retension, although all the plots are. `spladder test` with all other `--event-types` works just fine.

Hope you'll be able to help :)

Cheers,
Paulo

### What I Did

Used STAR aligned bam files (50bp single end reads) and Mouse ensembl annotation (Mus_musculus.GRCm38.102.chr.gtf)
```
STAR \
--runThreadN 14 \
--genomeDir $annotation \
--readFilesIn $fastq \
--outFileNamePrefix ../bam/$fastq \
--readFilesCommand bzcat -c \
--outSAMtype BAM SortedByCoordinate \
--outSAMstrandField intronMotif \
--outSAMattributes NH HI NM MD AS XS \
--outSAMheaderHD @HD   VN:1.4 \
--outFilterMultimapNmax 50 \
--outFilterMultimapScoreRange 3 \
--outFilterScoreMinOverLread 0.7 \
--outFilterMatchNminOverLread 0.7 \
--outFilterMismatchNmax 10 \
--alignIntronMax 500000 \
--alignMatesGapMax 1000000 \
--sjdbScore 2
```

```
spladder build -b alignments_list.txt -o spladder_out -a Mus_musculus.GRCm38.102.chr.gtf --parallel 16
```

```
spladder test -o spladder_out -a conditionA_list.txt -b conditionB_list.txt --readlen 50 --diagnose-plots -f pdf --parallel 16 --verbose --event-types intron_retention
```

Error:
```
Traceback (most recent call last):
  File "/home/paujan/miniconda3/envs/spladder/bin/spladder", line 33, in <module>
    sys.exit(load_entry_point('spladder==3.0.1', 'console_scripts', 'spladder')())
  File "/home/paujan/miniconda3/envs/spladder/lib/python3.10/site-packages/spladder-3.0.1-py3.10.egg/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/home/paujan/miniconda3/envs/spladder/lib/python3.10/site-packages/spladder-3.0.1-py3.10.egg/spladder/spladder_test.py", line 765, in spladder_test
    event_pos = np.array([_.get_exon_coordinate_strings() for _ in events])
  File "/home/paujan/miniconda3/envs/spladder/lib/python3.10/site-packages/spladder-3.0.1-py3.10.egg/spladder/spladder_test.py", line 765, in <listcomp>
    event_pos = np.array([_.get_exon_coordinate_strings() for _ in events])
  File "/home/paujan/miniconda3/envs/spladder/lib/python3.10/site-packages/spladder-3.0.1-py3.10.egg/spladder/classes/event.py", line 47, in get_exon_coordinate_strings
    _iso2 = np.array(['%i-%i' % (_[0], _[1]) for _ in self.exons2])
  File "/home/paujan/miniconda3/envs/spladder/lib/python3.10/site-packages/spladder-3.0.1-py3.10.egg/spladder/classes/event.py", line 47, in <listcomp>
    _iso2 = np.array(['%i-%i' % (_[0], _[1]) for _ in self.exons2])
IndexError: invalid index to scalar variable.
```

**Comment by akahles** [comment]
Dear @paulojannig ,

Thank you very much for reporting. I think I have found the bug and will update shortly.

Best,
Andre

**Comment by akahles** [comment]
I have now released version 3.0.2, which should address the problem. Please have a look. Will close this issue for now. Please re-open if still relevant.

Cheers,
Andre
