### ISSUE TITLE
Error in event calling - "Inf" in hdf5

### ISSUE THREAD

**Issue by deccagon** [ratschlab/spladder#161]
Hello @akahles ,
I am having a similar errors at event calling step with version 3.0.2 as [noted previously](https://github.com/ratschlab/spladder/issues/97#issuecomment-587957979).

I am following the steps from [large cohorts guide](https://spladder.readthedocs.io/en/latest/spladder_cohort.html). I get an error at the event calling step. 

Additionally, my merge_graphs.count.hdf5 has the same issues with `/Inf` as mentioned previously.

merge_graphs.count.hdf5:
```
h5ls -r spladder_out/spladder/genes_graph_conf3.merge_graphs.count.hdf5
/                        Group
/edge_idx                Dataset {436041}
/edges                   Dataset {436041, 92/Inf}
/gene_ids_edges          Dataset {436041, 1}
/gene_ids_segs           Dataset {744435, 1}
/gene_names              Dataset {67049, 1}
/samples                 Dataset {92/Inf}
/seg_len                 Dataset {744435, 1}
/seg_pos                 Dataset {744435, 92/Inf}
/segments                Dataset {744435, 92/Inf}
```

Command:
```
spladder build -o $outdir \
               -a $gtf \
               -b $bams \
               --use-anno-support \
               --output-conf-tcga \
               --verbose
```

Error output:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/path/to/envs/spladder/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/path/to/envs/spladder/lib/python3.8/site-packages/spladder/alt_splice/verify.py", line 520, in verify_wrapper
    ver, info = verify_mutex_exons(ev[i], genes[_g_idx], segments[:, s_idx].T,  np.c_[curr_edge_idx, edges[:, s_idx]], options)
  File "/path/to/envs/spladder/lib/python3.8/site-packages/spladder/alt_splice/verify.py", line 430, in verify_mutex_exons
    (options.use_anno_support and exon1 in set([(_[0], _[1]) for _ in np.hstack(gene.exons)])):
  File "<__array_function__ internals>", line 5, in hstack
  File "/path/to/envs/spladder/lib/python3.8/site-packages/numpy/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 12 and the array at index 1 has size 9
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/envs/spladder/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/path/to/envs/spladder/lib/python3.8/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/path/to/envs/spladder/lib/python3.8/site-packages/spladder/spladder_build.py", line 163, in spladder
    analyze_events(event_type, options.bam_fnames, options)
  File "/path/to/envs/spladder/lib/python3.8/site-packages/spladder/alt_splice/analyze.py", line 95, in analyze_events
    (events_all, counts, verified) = verify_all_events(events_all, np.arange(len(options.samples)), bam_fnames, event_type, options)
  File "/path/to/envs/spladder/lib/python3.8/site-packages/spladder/alt_splice/verify.py", line 590, in verify_all_events
    tmp = result.pop(0).get()
  File "/path/to/envs/spladder/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 12 and the array at index 1 has size 9
```
I am using Python 3.8.5, spladder 3.0.2. 

Thanks for all the effort you put into Spladder, and for your help in advance!

_Originally posted by @deccagon in https://github.com/ratschlab/spladder/issues/97#issuecomment-1073060929_

**Comment by deccagon** [comment]
I realized that this error was caused by BAM files that share the same name.
