### ISSUE TITLE
llvmlite.binding' has no attribute 'get_host_cpu_name

### ISSUE THREAD

**Issue by ArashDepp** [ratschlab/spladder#169]
* spladder version:3.0.0
* Python version:3.7
* Operating System:Linux

**### Description
I installed the package on linux cluster using pip. Installation was successfull. Here is the full list of messages that appeared during installation.**

Defaulting to user installation because normal site-packages is not writeable
Collecting spladder==3.0.0
  Downloading spladder-3.0.0-py2.py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 25.1 MB/s eta 0:00:00
Requirement already satisfied: h5py>=2.2 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (3.7.0)
Requirement already satisfied: pysam>=0.15.3 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (0.19.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (0.13.2)
Requirement already satisfied: scipy>=1.3 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (1.7.3)
Requirement already satisfied: intervaltree>=3.0.0 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (3.0.2)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (1.21.6)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from spladder==3.0.0) (3.5.2)
Requirement already satisfied: numba>=0.52.0 in ./.local/lib/python3.7/site-packages (from spladder==3.0.0) (0.56.0)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from intervaltree>=3.0.0->spladder==3.0.0) (2.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (4.34.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (9.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from matplotlib>=2.2->spladder==3.0.0) (1.4.3)
Requirement already satisfied: setuptools in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from numba>=0.52.0->spladder==3.0.0) (59.8.0)
Requirement already satisfied: importlib-metadata in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from numba>=0.52.0->spladder==3.0.0) (4.11.4)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in ./.local/lib/python3.7/site-packages (from numba>=0.52.0->spladder==3.0.0) (0.39.0)
Requirement already satisfied: pandas>=0.25 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from statsmodels>=0.9.0->spladder==3.0.0) (1.3.5)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from statsmodels>=0.9.0->spladder==3.0.0) (0.5.2)
Requirement already satisfied: typing-extensions in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.2->spladder==3.0.0) (3.10.0.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from pandas>=0.25->statsmodels>=0.9.0->spladder==3.0.0) (2022.1)
Requirement already satisfied: six in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from patsy>=0.5.2->statsmodels>=0.9.0->spladder==3.0.0) (1.16.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/Anaconda/envs/py3.7/lib/python3.7/site-packages (from importlib-metadata->numba>=0.52.0->spladder==3.0.0) (3.8.0)
Installing collected packages: spladder
Successfully installed spladder-3.0.0

### What I Did
Then I typed in the following command:
```
spladder build --help
Traceback (most recent call last):
  File "/home/singha30/.local/bin/spladder", line 5, in <module>
    from spladder.spladder import main
  File "/home/singha30/.local/lib/python3.7/site-packages/spladder/spladder.py", line 8, in <module>
    from .spladder_build import spladder
  File "/home/singha30/.local/lib/python3.7/site-packages/spladder/spladder_build.py", line 21, in <module>
    from .alt_splice.collect import collect_events
  File "/home/singha30/.local/lib/python3.7/site-packages/spladder/alt_splice/collect.py", line 10, in <module>
    from .detect import *
  File "/home/singha30/.local/lib/python3.7/site-packages/spladder/alt_splice/detect.py", line 3, in <module>
    from numba import jit
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/__init__.py", line 19, in <module>
    from numba.core import config
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 520, in <module>
    _env_reloader = _EnvReloader()
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 86, in __init__
    self.reset()
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 90, in reset
    self.update(force=True)
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 119, in update
    self.process_environ(new_environ)
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 340, in process_environ
    ENABLE_AVX = _readenv("NUMBA_ENABLE_AVX", int, avx_default)
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 150, in _readenv
    return default() if callable(default) else default
  File "/home/singha30/.local/lib/python3.7/site-packages/numba/core/config.py", line 336, in avx_default
    cpu_name = ll.get_host_cpu_name()
AttributeError: module 'llvmlite.binding' has no attribute 'get_host_cpu_name'
```

I mostly work with R and have very little experience with python. Could you please help me resolve this error? I tried multiple versions of Spladder (3 onwards) and all gave the same error. Your response is greatly appreciated.

**Comment by ArashDepp** [comment]
Hi.
Excuse me for following up but could you please take a look at this issue?

**Comment by akahles** [comment]
Dear @ArashDepp ,

Thanks a lot for reaching out. This looks like an issue with your environment, as numba is a just a dependency that SplAdder uses. So the error is not directly related to the SplAdder code. I would recommend to install SplAdder into a clean environment. You could do this by ether using a python `venv` (more information here https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) or using conda environments (more info here https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html).

Best,

Andre

**Comment by ArashDepp** [comment]
Hi Andre...
Thank you for suggestion. I got the issue fixed.
