### ISSUE TITLE
ValueError: NaN, inf or invalid value detected in endog, estimation infeasible

### ISSUE THREAD

**Issue by lisagrigoreva** [ratschlab/spladder#172]
Hello, 
I'm running Spladder under default settings, the graph was constructed successfully without any errors. 
However, the testing mode is crushed for 2 samples of my cohort. 
I'm already re-done the alignment for these samples but still getting the same error.
Thank you!

The error is:
```
/.conda/envs/riso/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/users/elizaveta.grigoreva/.conda/envs/riso/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/users/elizaveta.grigoreva/.conda/envs/riso/lib/python3.9/site-packages/spladder/spladder_test.py", line 81, in estimate_dispersion_chunk
    result = modNB.fit()
  File "/users/elizaveta.grigoreva/.conda/envs/riso/lib/python3.9/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1075, in fit
    return self._fit_irls(start_params=start_params, maxiter=maxiter,
  File "/users/elizaveta.grigoreva/.conda/envs/riso/lib/python3.9/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1213, in _fit_irls
    wls_mod = reg_tools._MinimalWLS(wlsendog, wlsexog,
  File "/users/elizaveta.grigoreva/.conda/envs/riso/lib/python3.9/site-packages/statsmodels/regression/_tools.py", line 52, in __init__
    raise ValueError(self.msg.format('endog'))
ValueError: NaN, inf or invalid value detected in endog, estimation infeasible.
"""
```

**Comment by akahles** [comment]
Dear @lisagrigoreva ,

Thanks a lot for reporting the issue. Can you please provide more details on your analysis setup? I would be interested in the following question:
* How many samples do you have?
* How did you generate the events that are tested (command line parameters)?
* How exactly did you test? How big are your groups?
* What is the remaining output of the test command (run in verbose mode)? How many events are being tested?

Thanks and Cheers,
Andre

**Comment by kate-stankiewicz** [comment]
Hello,

I am encountering a similar error. Was there any resolution to this?
