### ISSUE TITLE
viz mode issue

### ISSUE THREAD

**Issue by selmanurk** [ratschlab/spladder#173]
* whichever version is on conda
* 3.9
* Centos

### Description
Hi, 
I am trying to visualize test results, here is my code

### What I Did

```
spladder viz --test /truba/scratch/ikryvoruchko/selma/singlesplads/fullspladder/testing_Mutants_vs_Wild-Type exon_skip 2 -o ./fullspladder  --format png

and I get this error

Traceback (most recent call last):
  File "/truba/home/ikryvoruchko/miniconda3/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/truba/home/ikryvoruchko/miniconda3/lib/python3.9/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/truba/home/ikryvoruchko/miniconda3/lib/python3.9/site-packages/spladder/spladder_viz.py", line 262, in spladder_viz
    _parse_gene_info(range_info[1:], genes, gene_names, gids, all_gene_names, options.outdir, options.confidence, options.validate_sg, options.verbose)
  File "/truba/home/ikryvoruchko/miniconda3/lib/python3.9/site-packages/spladder/spladder_viz.py", line 79, in _parse_gene_info
    assert gid.shape[0] == 1
AssertionError
```

Do you have any idea why? Also, if I can get the test mode to work, can I filter where one condition doesn't have that splicing as condition_b_event_count=0 or log2FC_event_count=inf?

Thank you,
S

**Comment by akahles** [comment]
Dear @selmanurk ,

Thank you very much for reporting your issue. Can you send me the output of your test results?

Thanks,
Andre
