### ISSUE TITLE
About Image output 

### ISSUE THREAD

**Issue by avrajit** [ratschlab/spladder#183]
* spladder version:3.0.3
* Python version:3.9.15
* Operating System:20.04

### Description

I made a visualization  of my splicing result by using below command

### What I Did
spladder viz -o ./ --track event exon_skip.94
[gene_overview.pdf](https://github.com/ratschlab/spladder/files/10707341/gene_overview.pdf)

I like to know is this showing comparison between two sample condition(Group A and B)? or is it showing comparison with reference Genome? 

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by akahles** [comment]
Dear @avrajit ,

The command as shown just visualizes the alternative event. In your case this is an exon skip. Shown are the inclusion and the exclusion path of the event.

To also add the transcripts annotated for the respective gene (e.g., `gene1`), you would need to add `--track transcript gene1` to your plotting command. You can find more details on how to use the tracks in the [Spladder Documentation](https://spladder.readthedocs.io/en/latest/spladder_modes.html#general-organisation).

Best,
Andre

**Comment by avrajit** [comment]
Thanks for your response. I tried that way too. I did that with below command
spladder viz -o ./ --track transcript SPBC36B7.09

And the Error below. 

Traceback (most recent call last):
  File "/mypath/anaconda3/envs/spladder/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/mypath/anaconda3/envs/spladder/lib/python3.9/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/mypath/anaconda3/envs/spladder/lib/python3.9/site-packages/spladder/spladder_viz.py", line 256, in spladder_viz
    _parse_gene_info(range_info[1:], genes, gene_names, gids, all_gene_names, options.outdir, options.confidence, options.validate_sg, options.verbose)
  File "/mypath/anaconda3/envs/spladder/lib/python3.9/site-packages/spladder/spladder_viz.py", line 79, in _parse_gene_info
    assert gid.shape[0] == 1
AssertionError
