### ISSUE TITLE
Error with spladder_test: alt_5prime fails on scipy TypeError

### ISSUE THREAD

**Issue by warrenmcg** [ratschlab/spladder#20]
Hi Andre,

This has gotten even better with the introduction of the testing module! I was running it on my data, and I came across an error while the script was analyzing the alternative 5'ss events (the alt3_prime, intron retention, and exon skipping all worked fine).

Here is the traceback and the place where the script failed:

```
Testing alt_5prime events
Collecting intron confirmation values
Exclude 212 of 13393 alt_5prime events (1.58 percent) from testing due to low coverage
Estimating raw dispersions
[##################################################] 26350 / 26362 (100%) - took 499 sec (ETA: 0 sec)Found dispersion fit
Start to estimate adjusted dispersions.
[###################                               ] 10013 / 26362 (38%) - took 214 sec (ETA: 350 sec)Traceback (most recent call last):
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 859, in <module>
    main()
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 841, in main
    pvals = run_testing(cov, dmatrix0, dmatrix1, sf, CFG)
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 646, in run_testing
    (disp_adj, disp_adj_conv) = adjust_dispersion(cov, dmatrix1, disp_raw, disp_fitted, disp_idx, sf, CFG)
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 503, in adjust_dispersion
    (disp_adj, disp_adj_conv, _) = adjust_dispersion_chunk(counts, dmatrix1, disp_raw, disp_fitted, varPrior, sf, CFG, sp.arange(counts.shape[0]), log=CFG['verbose'])
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 447, in adjust_dispersion_chunk
    res = minimize_scalar(adj_loglikelihood_shrink_scalar_onedisper, args=(dmatrix1, resp, yhat, disp_fitted[i], varPrior, sign), method='Bounded', bounds=(0, 10.0), tol=1e-5)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/_minimize.py", line 608, in minimize_scalar
    return _minimize_scalar_bounded(fun, bounds, args, **options)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 1644, in _minimize_scalar_bounded
    fu = func(x, *args)
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 399, in adj_loglikelihood_shrink_scalar_onedisper
    loglik_adj = adj_loglikelihood_scalar(disp, explanatory, response, yhat, 1.0)
  File "/home/wulab2015linux/warren/Software/spladder_master/spladder/python/spladder_test.py", line 410, in adj_loglikelihood_scalar
    loglik = sum(nbinom.logpmf(y, n, p))
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/_distn_infrastructure.py", line 2862, in logpmf
    place(output, cond, self._logpmf(*goodargs))
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/_discrete_distns.py", line 167, in _logpmf
    return coeff + n*log(p) + special.xlog1py(x, -p)
```

Let me know if you need any other information. I'm happy to send you the offending HDF5 file (as well as one that was processed correctly) via email if that would help with debugging.

**Comment by akahles** [comment]
Hi Warren, thanks for reporting. Will try to look into this over the weekend.
Cheers,
Andre

**Comment by akahles** [comment]
I think this needs a little more work. For now, I enabled an option to get gene expression counts for normalization from non-alternative exon segments (`--non_alt_norm=y`) - this reduces the occurrence of the error drastically. The remaining few instances are caught and printed as warnings to the screen. 
Will need to discuss more with my coauthor in charge of the testing.

**Comment by akahles** [comment]
I believe this issue is no longer relevant. Please re-open if necessary.
