### ISSUE TITLE
Name Error: r_idx not found when using -R

### ISSUE THREAD

**Issue by jenzopr** [ratschlab/spladder#25]
Hi Andre!

When running spladder with 6 input files (3 x wt, 3 x ko), I run into an Name error as follows:

```
Traceback (most recent call last):
  File "/mnt/software/x86_64/packages/spladder/0.1/python/spladder.py", line 265, in <module>
    spladder()
  File "/mnt/software/x86_64/packages/spladder/0.1/python/spladder.py", line 261, in spladder
    analyze_events(CFG, CFG['event_types'][idx])
  File "/mnt/software/x86_64/packages/spladder/0.1/python/modules/alt_splice/analyze.py", line 51, in analyze_events
    rep_tag = '_R%i' % r_idx
NameError: global name 'r_idx' is not defined
```

I used the parameter -R to encode the replicates (-R 1,1,1,2,2,2). Hope the usage of -R was as intended?

Best,
Jens

**Comment by akahles** [comment]
Hi Jens,
The replicate feature is still somewhat experimental. Originally, I wanted to use that syntax for testing, but then decided differently. I will look into this soon and either remove that option or will re-define it in context of the merge-graphs step. 
Cheers,
Andre

**Comment by jenzopr** [comment]
Sounds good! Let me know if I can provide you with more details or additional data.

**Comment by Trandamere** [comment]
Hi Andre!
i also have the problem with the replicates
 Traceback (most recent call last):
  File "spladder.py", line 322, in <module>
    spladder()
  File "spladder.py", line 318, in spladder
    analyze_events(CFG, CFG['event_types'][e_idx])
  File "/home/luping/spladder-master/python/modules/alt_splice/analyze.py", line 54, in analyze_events
    rep_tag = '_R%i' % r_idx
NameError: global name 'r_idx' is not defined

This is my code
python spladder.py -a /disk/luping/bam/merged.gtf -o /home/luping/spladder-master/spladderesult --parallel=10 -R 1,1,1,2,2,2 -b /disk/luping/bam/Coni_1.bam,/disk/luping/bam/Coni_2.bam,/disk/luping/bam/Coni_3.bam,/disk/luping/bam/Ger12h_1.bam,/disk/luping/bam/Ger12h_2.bam,/disk/luping/bam/Ger12h_3.bam

Did i have any mistake?

**Comment by akahles** [comment]
The replicate parameter has been removed from the latest versions of spladder in `build` mode.
