### ISSUE TITLE
error during loading introns

### ISSUE THREAD

**Issue by lxu3** [ratschlab/spladder#28]
Hi, 

SplAdder produces the following error:

Augmenting splice graphs.
=========================
Generating splice graph ...
...done.

Loading introns from file ...

Traceback (most recent call last):
  File ".../spladder-master/python/spladder.py", line 318, in <module>
    spladder()
  File ".../spladder-master/python/spladder.py", line 223, in spladder
    spladder_core(CFG)
  File ".../spladder-master/python/modules/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, CFG)
  File ".../spladder-master/python/modules/core/gen_graphs.py", line 83, in gen_graphs
    introns = get_intron_list(genes, CFG)
  File ".../spladder-master/python/modules/reads.py", line 431, in get_intron_list
    [intron_list_tmp] = add_reads_from_bam(gg, CFG['bam_fnames'], ['intron_list'], CFG['read_filter'], CFG['var_aware'], CFG['primary_only'], CFG['ignore_mismatch_tag'])
  File ".../spladder-master/python/modules/reads.py", line 155, in add_reads_from_bam
    (introns, spliced_coverage) = get_all_data(blocks[b], filenames, mapped=False, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File ".../spladder-master/python/modules/reads.py", line 314, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File ".../spladder-master/python/modules/reads.py", line 43, in get_reads
    if filter_read(read, filter, spliced, mapped, strand, primary_only, var_aware, no_mm):
  File ".../spladder-master/python/modules/reads.py", line 454, in filter_read
    is_spliced = ('N' in read.cigarstring)
AttributeError: 'csamtools.AlignedRead' object has no attribute 'cigarstring'

My command is:
python .../spladder-master/python/spladder.py -a .../0-annotation-file/gencode.v19.annotation.gff3 -b .../sorted.bam -o ../output

Would you mind helping me to fix this problem? Thanks!

Lin

**Comment by akahles** [comment]
Hi Lin,
Thank your for using SplAdder. Which version of pysam are you using? You can check this in python via:
```
import pysam
pysam.__version__
```
SplAdder requires pysam to be at least version 0.7 to function properly.

Cheers,
Andre

**Comment by lxu3** [comment]
Hi, Andre

Thank you very much for your quick reply. I noticed my pysam version is 0.6 so I will update to 0.7 or higher. I will re-run it after the upgrade and let you know whether it works.

Thanks!
Lin
