### ISSUE TITLE
KeyError?

### ISSUE THREAD

**Issue by fletcher-m** [ratschlab/spladder#43]
Hello,

I've pulled the latest commit from the master branch and I'm getting the following error when I run spladder.py:

```
python /home/fletcher/spladder/spladder/python/spladder.py -b ${BAM_LIST} -o ${OUTPUT_DIR} -a ${GENCODE_GTF} -l ${LOG_FILE}
Augmenting splice graphs.
=========================
Traceback (most recent call last):
  File "/home/fletcher/spladder/spladder/python/spladder.py", line 322, in <module>
    spladder()
  File "/home/fletcher/spladder/spladder/python/spladder.py", line 223, in spladder
    spladder_core(CFG)
  File "/home/fletcher/spladder/spladder/python/modules/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/home/fletcher/spladder/spladder/python/modules/core/gen_graphs.py", line 83, in gen_graphs
    introns = get_intron_list(genes, CFG)
  File "/home/fletcher/spladder/spladder/python/modules/reads.py", line 431, in get_intron_list
    [intron_list_tmp] = add_reads_from_bam(gg, CFG['bam_fnames'], ['intron_list'], CFG['read_filter'], CFG['var_aware'], CFG['primary_only'], CFG['ignore_mismatch_tag'])
  File "/home/fletcher/spladder/spladder/python/modules/reads.py", line 155, in add_reads_from_bam
    (introns, spliced_coverage) = get_all_data(blocks[b], filenames, mapped=False, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File "/home/fletcher/spladder/spladder/python/modules/reads.py", line 314, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/home/fletcher/spladder/spladder/python/modules/reads.py", line 43, in get_reads
    if filter_read(read, filter, spliced, mapped, strand, primary_only, var_aware, no_mm):
  File "/home/fletcher/spladder/spladder/python/modules/reads.py", line 472, in filter_read
    return filter['mismatch'] < tags['NM']
KeyError: 'NM'
```

A bit of googling suggests that this is some sort of dictionary error, but I don't know enough about the code to figure out why. Is there a solution?

**Comment by akahles** [comment]
Hi,

SplAdder expects the input alignments to provide the NM tag, indicating the number of edit operations per alignment. If this information is missing, SplAdder will not be able to use its internal filters. If you cannot add this information to you alignment files, you can run SplAdder in a mode that omits any filtering on alignment quality via the command line switch: ```--ignore_mismatches y```

However, I see the point that the error message should be more enlightening.

**Comment by akahles** [comment]
Added an error message. Please re-open if the issue pops up again.
