### ISSUE TITLE
[spladder_test.py on Linux x86_64, python 2.7] TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by dnrichardson** [ratschlab/spladder#45]
Hello Andre,

Thanks for the wonderful program! I'm running an analysis on _Arabidopsis thaliana_ using the TAIR10.gff, with modified chromosome names (i.e. Chr1 -- > 1). I've successfully run spladder.py on my data, but when trying to run spladder_test.py without specifying -t, thusly: 

`python spladder_test.py -o my_output -a ../../WT2SAligned.sortedByCoord.out.bam,../../WT3SAligned.sortedByCoord.out.bam -b ../../KO1SAligned.sortedByCoord.out.bam,../../KO3SAligned.sortedByCoord.out.bam —labelA=Wildtype —labelB=Knockout -n 125 -c 3 —timestamp=y`

The following error crops up after successfully processing the skipped exons class (I have a test_results_C3_exon_skip.tsv file in the testing folder):

`Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/Users.nfs.haystack01a/drichardson/newscl30a/spladder/python/modules/alt_splice/quantify.py", line 516, in quantify_from_counted_events
    event_ids = get_event_ids(IN, event_type, event_idx, CFG)
  File "/home/Users.nfs.haystack01a/drichardson/newscl30a/spladder/python/modules/alt_splice/quantify.py", line 677, in get_event_ids
    event_ids0 = sp.array(['%s:%s' % (gene_chr[i], '-'.join(IN['event_pos'][i, [1, 2]].astype('str'))) for i in event_idx], dtype='str')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "/Users/drichardson/anaconda3/envs/bunnies/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/Users/drichardson/anaconda3/envs/bunnies/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/Users/drichardson/anaconda3/envs/bunnies/lib/python2.7/site-packages/h5py/_hl/selections.py", line 382, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape, vector)
  File "/Users/drichardson/anaconda3/envs/bunnies/lib/python2.7/site-packages/h5py/_hl/selections.py", line 447, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/Users/drichardson/anaconda3/envs/bunnies/lib/python2.7/site-packages/h5py/_hl/selections.py", line 467, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (2) out of range (0-1)
`

Trying to specify the type of event fails for all event types, even exon_skip, which was previously successfully processed! 

`python spladder_test.py -o my_output -a ../../WT2SAligned.sortedByCoord.out.bam,../../WT3SAligned.sortedByCoord.out.bam -b ../../KO1SAligned.sortedByCoord.out.bam,../../KO3SAligned.sortedByCoord.out.bam —labelA=Wildtype —labelB=Knockout -n 125 -c 3 —timestamp=y -t exon_skip`

`Traceback (most recent call last):
  File "spladder_test.py", line 920, in <module>
    main()
  File "spladder_test.py", line 796, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], idx1, idx2, event_type, CFG)
  File "/home/Users.nfs.haystack01a/drichardson/newscl30a/spladder/python/modules/alt_splice/quantify.py", line 391, in quantify_from_counted_events
    if CFG['is_matlab']:
TypeError: string indices must be integers, not str
`

After browsing through the issues here, I thought to try the development version of spladder. When trying to run the development version of spladder_test.py, I get the following error:

`Traceback (most recent call last):
  File "spladder_test.py", line 920, in <module>
    main()
  File "spladder_test.py", line 765, in main
    gene_counts, gene_strains, gene_ids = get_gene_expression(CFG, fn_out=CFG['fname_exp_hdf5'], strain_subset=condition_strains)
  File "spladder_test.py", line 171, in get_gene_expression
    gene_counts[gidx, :] = sp.dot(IN['segments'][seg_idx, :][:, strain_idx].T, seg_lens[seg_idx]) / CFG['read_length']
ValueError: could not broadcast input array from shape (4,1) into shape (4)`

So.. at the moment I'm at a little bit of a loss as to how to resolve this. What files would you need from me to help figure out what is going on? 

Thanks so much for your help!

**Comment by dnrichardson** [comment]
Just wanted to give a quick update: I think I've been able to solve the issue, at least regarding the development version of spladder_test.py. Running spladder_test.py within the pdb environment, I was able to hone in on what was throwing the error. Line 171 of spladder_test.py,

`if seg_idx.shape[0] > 1:
                gene_counts[gidx, :] = sp.dot(IN['segments'][seg_idx, :][:, strain_idx].T, seg_lens[seg_idx]) / CFG['read_length']`

was causing an error because the array returned by sp.dot had an extra dimension that gene_counts was not initialized for. 

Changing the offending line to:

`gene_counts[gidx, :] = sp.squeeze(sp.dot(IN['segments'][seg_idx, :][:, strain_idx].T, seg_lens[seg_idx]) / CFG['read_length']).flatten()`

Seems to have fixed the problem as I am now able to run spladder_test.py successfully (at least for exon_skip and ret_intron -- I'm still testing the other cases). 

Will close the issue! 

Thanks,
Dale
