### ISSUE TITLE
Error while running spladder_test.py

### ISSUE THREAD

**Issue by asgarhussain** [ratschlab/spladder#46]
Hi Andre,
I am having following problem while running spladder_test.py :

 /home/asgar.hussain/anaconda2/bin/python2.7 /home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py -o 150_CC_as_events_conf3_GENCODE/ -a 150_CC_as_events_conf3_GENCODE/merge_graphs_exon_skip_C3.counts.hdf5 -b 150_FC_as_events_conf3_GENCODE/merge_graphs_exon_skip_C3.counts.hdf5 
Traceback (most recent call last):
  File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 873, in <module>
    main()
  File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/scratch/asgar.hussain/tools/spladder-master/python/modules/alt_splice/quantify.py", line 508, in quantify_from_counted_events
    cov[0] += IN['event_counts'][strain_idx, f[0], :][:, event_idx].T
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "/home/asgar.hussain/anaconda2/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/asgar.hussain/anaconda2/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/home/asgar.hussain/anaconda2/lib/python2.7/site-packages/h5py/_hl/selections.py", line 388, in __getitem__
    mshape = list(count)
UnboundLocalError: local variable 'count' referenced before assignment

**Comment by akahles** [comment]
Hi Asgar,
Sorry that the usage is not quite clear from the wiki. It is high up on my list to extend the usage instructions ... Anyway, the options `-a` and `-b` get comma separated lists of bam files you would like to test (all or a subset of the ones you provided for quantification earlier). The files will not be accessed directly, but their names will be used to find the correct counts in the internal data structures.

Cheers,
Andre

**Comment by akahles** [comment]
I just see that you run spladder twice. The way it is supposed to be run is as follows: The graph generation step and counting on all the bam files together. Only during testing, subsets of files are used. Sorry that this is not more clear from the instructions, I will add more information soon.

**Comment by asgarhussain** [comment]
Hi Andre,
I used the following command for quantification:
/home/asgar.hussain/anaconda2/bin/python2.7 /home/asgar.hussain/scratch/tools/spladder-master/python/spladder.py -b 150_CC_TGACCA_L001_merged_sort.bam.bam,150_FC_CGATGT_L001_merged_sort.bam.bam -a gencode.v19.annotation.gtf -o tmp   --parallel=6

Later for differential expression, I used the following command :
/home/asgar.hussain/anaconda2/bin/python2.7 /home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py -o tmp -a 150_CC_TGACCA_L001_merged_sort.bam.bam -b 150_FC_CGATGT_L001_merged_sort.bam.bam
Traceback (most recent call last):
  File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 873, in <module>
    main()
  File "/home/asgar.hussain/scratch/tools/spladder-master/python/spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/scratch/asgar.hussain/tools/spladder-master/python/modules/alt_splice/quantify.py", line 508, in quantify_from_counted_events
    cov[0] += IN['event_counts'][strain_idx, f[0], :][:, event_idx].T
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "/home/asgar.hussain/anaconda2/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/asgar.hussain/anaconda2/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/home/asgar.hussain/anaconda2/lib/python2.7/site-packages/h5py/_hl/selections.py", line 388, in __getitem__
    mshape = list(count)
UnboundLocalError: local variable 'count' referenced before assignment

Please tell me, what I am doing wrong ?

**Comment by akahles** [comment]
I don't see anything obviously wrong with your calls. Does this occur on the last release, the master or the development branch?

**Comment by asgarhussain** [comment]
It occurs on the spladder-master.

**Comment by asgarhussain** [comment]
Hi Andre,
I am still getting the above mentioned problem, Can you please look into this.

Regards,
Asgar

**Comment by akahles** [comment]
Hi Asgar,
Sorry for the late reply. I have difficulties reproducing your error. Would it be possible to share a small part of your input files with me? A fraction would be enough (e.g. chr22). It is also fine, if you replace read and quality strings in the BAMs (to preserve privacy) - SplAdder does not access this information. 
Thanks and Cheers,
Andre

**Comment by asgarhussain** [comment]
Hi Andre,
I have attached bam files. I provide gencode.v19.annotation  as a annotation file. 
[spladder_input.zip](https://github.com/ratschlab/spladder/files/588491/spladder_input.zip)
 Thanks
Asgar

**Comment by Trandamere** [comment]
Hi Andre,
I used the following command for differential expression 

python spladder_test.py -o /home/luping/spladder-master/spladder-GLM/ -a /disk//bam/Coni_1.bam,/disk/luping/bam/Coni_2.bam,/disk/bam/Coni_3.bam  -b /disk/bam/Ger12h_1.bam,/disk/bam/Ger12h_2.bam,/disk/bam/Ger12h_3.bam --parallel=10
Traceback (most recent call last):
  File "spladder_test.py", line 873, in <module>
    main()
  File "spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/luping/spladder-master/python/modules/alt_splice/quantify.py", line 388, in quantify_from_counted_events
    IN = h5py.File(event_fn, 'r', driver='core')
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/luping/sf/python/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-3TLvcq-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-3TLvcq-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file)

I don't know how to fix it.

**Comment by akahles** [comment]
Can you please send me your original spladder call? The one starting with `python spladder.py ...`?

**Comment by akahles** [comment]
Please re-open if the problem persists with the latest SplAdder release.
