### ISSUE TITLE
ValueError: no index available for iteration

### ISSUE THREAD

**Issue by khericlim** [ratschlab/spladder#47]
Test ran using the exact parameters from `example_run.sh`, minus bam and gtf, and got the following error.

```
$ python2.7 spladder.py -b test.bam -o test/ -a Homo_sapiens.GRCh37.82.gtf -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n

Augmenting splice graphs.
=========================
Generating splice graph ...

Total genes:							57905
Total genes with alternative isoforms:				22172
Total genes alternatively spliced:				21857
Total constitutively spliced:					36048
...done.

Loading introns from file ...
Traceback (most recent call last):
  File "spladder.py", line 322, in <module>
    spladder()
  File "spladder.py", line 223, in spladder
    spladder_core(CFG)
  File "/Users/ericlim/Data/scratch/spladder/python/modules/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/Users/ericlim/Data/scratch/spladder/python/modules/core/gen_graphs.py", line 83, in gen_graphs
    introns = get_intron_list(genes, CFG)
  File "/Users/ericlim/Data/scratch/spladder/python/modules/reads.py", line 431, in get_intron_list
    [intron_list_tmp] = add_reads_from_bam(gg, CFG['bam_fnames'], ['intron_list'], CFG['read_filter'], CFG['var_aware'], CFG['primary_only'], CFG['ignore_mismatch_tag'])
  File "/Users/ericlim/Data/scratch/spladder/python/modules/reads.py", line 155, in add_reads_from_bam
    (introns, spliced_coverage) = get_all_data(blocks[b], filenames, mapped=False, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File "/Users/ericlim/Data/scratch/spladder/python/modules/reads.py", line 314, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/Users/ericlim/Data/scratch/spladder/python/modules/reads.py", line 40, in get_reads
    for read in infile.fetch(chr_name, start, stop, until_eof=True):
  File "pysam/calignmentfile.pyx", line 915, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:11287)
  File "pysam/calignmentfile.pyx", line 1751, in pysam.calignmentfile.IteratorRowRegion.__init__ (pysam/calignmentfile.c:19179)
ValueError: no index available for iteration
```

**Comment by akahles** [comment]
Does your input file `test.bam` have the corresponding index `test.bam.bai` present at the same location?

**Comment by khericlim** [comment]
Thanks. Including the index solves the problem.
