### ISSUE TITLE
ValueError: setting array element with a sequence

### ISSUE THREAD

**Issue by chartl** [ratschlab/spladder#48]
```
Make intron_retention events unique by strain
. . . events dropped: 0
Traceback (most recent call last):
  File "/u/Software/spladder/python/spladder.py", line 322, in <module>
    spladder()
  File "/u/Software/spladder/python/spladder.py", line 311, in spladder
    collect_events(CFG)
  File "/u/Software/spladder/python/modules/alt_splice/collect.py", line 371, in collect_events
    events_all = post_process_event_struct(intron_reten_pos_all, CFG)
  File "/u/Software/spladder/python/modules/alt_splice/events.py", line 62, in post_process_event_struct
    events = sort_events_by_event(events, CFG)
  File "/u/Software/spladder/python/modules/alt_splice/events.py", line 27, in sort_events_by_event
    coord_list = sp.array([x.get_inner_coords() for x in event_list], dtype='double')
ValueError: setting an array element with a sequence.

```

One of my spladder runs failed recently with the (above) error. The stack trace pointed to the definition of `coord_list` in the following code:

```
#/modules/classes/event.py
def sort_events_by_event(event_list, CFG):
    # event_list = sort_events_by_event(event_list, CFG),

    coord_list = sp.array([x.get_inner_coords() for x in event_list], dtype='double')
    chr_list = sp.array([CFG['chrm_lookup'][x.chr] for x in event_list], dtype='double')
    strand_list = sp.array([x.strand == '-' for x in event_list], dtype='double')
    sort_list = sp.c_[chr_list, strand_list, coord_list]
    tmp, idx = sort_rows(sort_list, index=True)

    return event_list[idx]

```

It appears the `event.get_inner_coords()` method can return arrays of different dimension depending on splice event type; and the dimensions all need to match in order to set the dtype of the array to `double`.

Setting the type to `'O'` fixes this error, but breaks the later sort:

```
Traceback (most recent call last):
  File "/u/Software/spladder/python/spladder.py", line 322, in <module>
    spladder()
  File "/u/Software/spladder/python/spladder.py", line 311, in spladder
    collect_events(CFG)
  File "/u/Software/spladder/python/modules/alt_splice/collect.py", line 371, in collect_events
    events_all = post_process_event_struct(intron_reten_pos_all, CFG)
  File "/u/Software/spladder/python/modules/alt_splice/events.py", line 62, in post_process_event_struct
    events = sort_events_by_event(events, CFG)
  File "/u/Software/spladder/python/modules/alt_splice/events.py", line 31, in sort_events_by_event
    tmp, idx = sort_rows(sort_list, index=True)
  File "/u/Software/spladder/python/modules/utils.py", line 106, in sort_rows
    s_idx = sp.lexsort([array[:, -i] for i in range(1, array.shape[1] + 1)])
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

Current setup: 

```

$ python --version
Python 2.7.3

$ pip freeze
cycler==0.10.0
h5py==2.6.0
matplotlib==1.5.3
numpy==1.11.2
pyparsing==2.1.10
pysam==0.9.1.4
python-dateutil==2.6.0
pytz==2016.10
scipy==0.18.1
six==1.10.0

```

**Comment by akahles** [comment]
Hi chartl,

Thanks for reporting. Are you working on the latest release, the master branch or the development branch?

Thanks, 
Andre

**Comment by chartl** [comment]
Master branch.

-Chris

**Comment by martinjvickers** [comment]
I'm getting this error too, master branch checked out last week. Is there a resolution to this?

**Comment by nicweb** [comment]
I'm also running into this. Any update on a solution?

**Comment by akahles** [comment]
Sorry that this took so long. I had difficulties to reproduce this but finally figured out how this happened. Should be fixed now (in the development branch), please re-open if issue should still persist.

**Comment by pkohvaei** [comment]
@akahles : I think the zip version of spladder still contains the old code from this thread. Could you please check?
