### ISSUE TITLE
spladder_test TypeError

### ISSUE THREAD

**Issue by ramaniak** [ratschlab/spladder#56]
Hello,
I recently used spladder for my data and followed the python documentation to run the augmentation and event detection phases. These seemed to run successfully and I generated the pickle and hd5 files.

When I ran the tutorial (test run) with the data provided, I generated the following files in my results directory:

```
spladder/genes_graph_conf3.NMD_DBL2.tiny.pickle
spladder/genes_graph_conf3.NMD_WT1.tiny.pickle
spladder/genes_graph_conf3.NMD_WT2.tiny.pickle
spladder/genes_graph_conf3.NMD_DBL1.tiny.pickle
spladder/genes_graph_conf3.merge_graphs.pickle	       
spladder/genes_graph_conf3.merge_graphs.count.hdf5   

```
This seems to be one difference: I get a count.hdf5 instead of count.pickle as written in the documentation. Is this okay?

the subsequent step of "event detection" runs fine. I therefore assume this was not an issue and proceeded with my data for augumentation and event_detection. They also proceeded without any errors.

I am not trying to run the spladder_test on a subset of my data and get the following error:

```
python spladder_test.py -o results  -a DIPG100N.sorted.mdup,DIPG14BN.sorted.mdup,DIPG27N.sorted.mdup -b DIPG112WM.sorted.mdup,DIPG109WM.sorted.mdup,DIPG100WM.sorted.mdup 

Traceback (most recent call last):
  File "/hpf/largeprojects/ccmbio/arun/Tools/spladder/python/spladder_test.py", line 873, in <module>
    main()
  File "/hpf/largeprojects/ccmbio/arun/Tools/spladder/python/spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/hpf/largeprojects/ccmbio/arun/Tools/spladder/python/modules/alt_splice/quantify.py", line 508, in quantify_from_counted_events
    cov[0] += IN['event_counts'][strain_idx, f[0], :][:, event_idx].T
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/hpf/tools/centos6/python/source/packages/h5py-2.5.0/h5py/_objects.c:2472)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/hpf/tools/centos6/python/source/packages/h5py-2.5.0/h5py/_objects.c:2429)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 431, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/selections.py", line 95, in select
    sel[args]
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/selections.py", line 429, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order


```

I did a search on the issues and did not find any previous posts about this. I was wondering if you could point me in the right direction to get this working?

thanks
Arun

**Comment by akahles** [comment]
I believe this got resolved in the recent versions of SplAdder. Please re-open if the issue still persists.
