### ISSUE TITLE
Attribute error when validating splice graph

### ISSUE THREAD

**Issue by hvbakel** [ratschlab/spladder#60]
When running spladder.py with the "-V y" option, I'm encountering the following error:

```
Store genes at: spladder_T6IFFR_vs_T6IFSM/spladder/genes_graph_conf3.merge_graphs.pickle
Traceback (most recent call last):
  File "/hpc/users/opt/spladder//python/spladder.py", line 328, in <module>
    spladder()
  File "/hpc/users/opt/spladder//python/spladder.py", line 247, in spladder
    genes = filter_by_edgecount(genes, CFG)
  File "/hpc/users/opt/spladder/python/modules/editgraph.py", line 250, in filter_by_edgecount
    k_idx = sp.where(genes[i].splicegraph.edges.sum(axis = 1) == 0)[0]
AttributeError: 'NoneType' object has no attribute 'sum'
```
Note that I'm using the development branch of spladder.

**Comment by akahles** [comment]
Dear hvbakel,
This error occurred when the spare BAM representation was used. It should be fixed in the current code. 

Please re-open if still revelant.
