### ISSUE TITLE
AttributeError: Values instance has no attribute 'splicegraph' when example_viz.sh 

### ISSUE THREAD

**Issue by cfyin** [ratschlab/spladder#67]
##spladder.py version 1.1.0 in python
$ ./exampe.sh
......
ALL RESULT FILES ARE CORRECT.
$ ./example_viz.sh 
Traceback (most recent call last):
  File "spladder_viz.py", line 297, in <module>
    spladder_viz()
  File "spladder_viz.py", line 80, in spladder_viz
    CFG = settings.parse_args(options, identity='viz')
  File "/tools/spladder-1.1.0/python/modules/settings.py", line 384, in parse_args
    if options.splicegraph in ['n', 'y']:
AttributeError: Values instance has no attribute 'splicegraph'

**Comment by akahles** [comment]
The `example_viz.sh` is no longer used in the recent releases of SplAdder.
