### ISSUE TITLE
AttributeError: 'IntervalTree' object has no attribute 'search' 

### ISSUE THREAD

**Issue by Kai4010** [ratschlab/spladder#73]
When running spladder.py, I'm encountering the following error:

$ python spladder.py -a Mus_musculus.GRCm38.93.gtf -b Wt.bam,Mu.bam -o /test -T y 

```
Augmenting splice graphs.
=========================
Generating splice graph ...
...done.

Loading introns from file ...
...done.

Filtering introns for ambiguity ...
Traceback (most recent call last):
  File "spladder.py", line 325, in <module>
    spladder()
  File "spladder.py", line 226, in spladder
    spladder_core(CFG)
  File "/home/yosuke/spladder/python/modules/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/home/yosuke/spladder/python/modules/core/gen_graphs.py", line 86, in gen_graphs
    introns = filter_introns(introns, genes, CFG)
  File "/home/yosuke/spladder/python/modules/helpers.py", line 69, in filter_introns
    if len(gene_trees[(s, genes[i].chr)].search(introns[i, si][j, 0] - offset, introns[i, si][j, 1] + offset)) == 1:
AttributeError: 'IntervalTree' object has no attribute 'search'
```

**Comment by akahles** [comment]
Dear Kai4010,
Thank you very much for reporting. This is due to a change of API in IntervalTree. I have pushed a fix that should resolve the issue. Please re-open, if necessary.
Cheers,
Andre
