### ISSUE TITLE
ValueError: no index available for iteration

### ISSUE THREAD

**Issue by upendrak** [ratschlab/spladder#77]
* spladder version:1.0.0
* Python version: 2.7.6
* Operating System: Ubuntu 14.04.3 LTS

### Description

I am trying to run Spladder but for some reason eventhough my gff3 and bam files are correct, it is throwing "ValueError: no index available for iteration" error. I don't know what I am doing wrong.

### What I Did

```
python /spladder-1.0.0/python/spladder.py -b output/TCS10-1-A7_trimmed.sorted.bam,output/TCS10-2-A8_trimmed.sorted.bam,output/TCS10-3-A9_trimmed.sorted.bam,output/THS10-1-A10_trimmed.sorted.bam,output/THS10-2-A11_trimmed.sorted.bam,output/THS10-3-A12_trimmed.sorted.bam,output/THS5.1.A4_trimmed.sorted.bam,output/THS5.2.A5_trimmed.sorted.bam,output/THS5.3.A6_trimmed.sorted.bam -o Outputpre -a Fragaria_vesca_v4.0.a1.transcripts.gff3 -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n -P n
WARNING: Output directory Outputpre does not exist - will be created


Parsing annotation from Fragaria_vesca_v4.0.a1.transcripts.gff3 ...
... init structure
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ... done
Storing gene structure in Fragaria_vesca_v4.0.a1.transcripts.gff3.pickle ...
... done
/spladder-1.0.0/python/modules/editgraph.py:924: RuntimeWarning: divide by zero encountered in double_scalars
  (sp.median(exon_cov[-min_len_aft:]) / sp.median(aft_segment_cov[:min_len_aft])) - 1 >= CFG['cassette_exon']['min_cassette_rel_diff'] and \
/spladder-1.0.0/python/modules/editgraph.py:925: RuntimeWarning: divide by zero encountered in double_scalars
  (sp.median(exon_cov[:min_len_pre]) / sp.median(pre_segment_cov[-min_len_pre:])) - 1 >= CFG['cassette_exon']['min_cassette_rel_diff']:
Traceback (most recent call last):
  File "/spladder-1.0.0/python/spladder.py", line 309, in <module>
    spladder()
  File "/spladder-1.0.0/python/spladder.py", line 225, in spladder
    spladder_core(CFG)
  File "/spladder-1.0.0/python/modules/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/spladder-1.0.0/python/modules/core/gen_graphs.py", line 83, in gen_graphs
    introns = get_intron_list(genes, CFG)
  File "/spladder-1.0.0/python/modules/reads.py", line 431, in get_intron_list
    [intron_list_tmp] = add_reads_from_bam(gg, CFG['bam_fnames'], ['intron_list'], CFG['read_filter'], CFG['var_aware'], CFG['primary_only'], CFG['ignore_mismatch_tag'])
  File "/spladder-1.0.0/python/modules/reads.py", line 155, in add_reads_from_bam
    (introns, spliced_coverage) = get_all_data(blocks[b], filenames, mapped=False, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File "/spladder-1.0.0/python/modules/reads.py", line 314, in get_all_data
    (coverage_tmp, introns_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/spladder-1.0.0/python/modules/reads.py", line 40, in get_reads
    for read in infile.fetch(chr_name, start, stop, until_eof=True):
  File "pysam/calignmentfile.pyx", line 899, in pysam.calignmentfile.AlignmentFile.fetch (pysam/calignmentfile.c:11146)
  File "pysam/calignmentfile.pyx", line 1727, in pysam.calignmentfile.IteratorRowRegion.__init__ (pysam/calignmentfile.c:19123)
ValueError: no index available for iteration
```

**Comment by akahles** [comment]
Dear upendrak,

Thank you very much for reporting. Can you please try with a newer version of SplAdder (1.2.1 for Python 2.7 or 2.0.0 for Python 3.0)? Please post here, if the error still persists.

Best,
Andre

**Comment by upendrak** [comment]
@akahles thanks. I will try both and report back.

**Comment by upendrak** [comment]
@akahles I am again getting a similar error in Python 3.0. Is it anything to do with my input files? The gtf and bam files looked fine to me.

```spladder build -b TCS10-1-A7_trimmed.sorted.bam -o spladder_out -a Fragaria_vesca_v4.0.a1.transcripts.gff3 
WARNING: Output directory spladder_out does not exist - will be created


Augmenting splice graphs.
=========================
Generating splice graph ...
...done.

Loading introns from file ...
Traceback (most recent call last):
  File "/usr/local/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder.py", line 182, in main
    options.func(options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder_build.py", line 148, in spladder
    spladder_core(options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/core/spladdercore.py", line 21, in spladder_core
    genes = gen_graphs(genes, options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/core/gen_graphs.py", line 79, in gen_graphs
    introns = get_intron_list(genes, options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/reads.py", line 462, in get_intron_list
    [intron_list_tmp] = add_reads_from_bam(gg, options.bam_fnames, ['intron_list'], options.read_filter, options.var_aware, options.primary_only, options.ignore_mismatches, unstranded=options.introns_unstranded)
  File "/usr/local/lib/python3.6/dist-packages/spladder/reads.py", line 176, in add_reads_from_bam
    (introns_p, introns_m, spliced_coverage) = get_all_data(blocks[b], filenames, mapped=False, filter=filter, var_aware=var_aware, primary_only=primary_only, no_mm=no_mm)
  File "/usr/local/lib/python3.6/dist-packages/spladder/reads.py", line 342, in get_all_data
    (coverage_tmp, introns_p_tmp, introns_m_tmp) = get_reads(fname, contig_name, block.start, block.stop, strand, filter, mapped, spliced, var_aware, collapse, primary_only, no_mm)
  File "/usr/local/lib/python3.6/dist-packages/spladder/reads.py", line 42, in get_reads
    for read in infile.fetch(chr_name, start, stop, until_eof=True):
  File "pysam/libcalignmentfile.pyx", line 1091, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libcalignmentfile.pyx", line 2056, in pysam.libcalignmentfile.IteratorRowRegion.__init__
ValueError: no index available for iteration
```

**Comment by akahles** [comment]
Could you please send me the first 100 lines of your bam file (e.g., via `samtools view BAMFILE | head -n 100`) and the first 100 lines of your gtf file?

**Comment by upendrak** [comment]
@akahles here are the files. Thanks

[input_data.zip](https://github.com/ratschlab/spladder/files/2975852/input_data.zip)

**Comment by akahles** [comment]
Ok. One more question. Are your bam files indexed? SplAdder assumes that for a given BAM file `alignment.bam` also its index file `alignment.bam.bai` is present at the same location.

**Comment by upendrak** [comment]
@akahles you know what I was being stupid. I was testing spladder on the bam files without `.bai` file. When I included the `.bai` file. It worked. Sorry for the trouble and thanks for your patience.

**Comment by akahles** [comment]
No worries. Apologies that it took so long for me to catch this. I will add a check to give the user a more meaningful warning.
