### ISSUE TITLE
ValueError: unsupported pickle protocol: 4

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#81]
* spladder version: 1.2.1
* Python version: 2.7.12
* Operating System: Ubuntu 16.04

### Description

After hitting a bug with the latest spladder (#71) I installed 1.2.1 ('pip install spladder==1.2.1 --user'), rewrote my BAM files substituting the "NM" tag for the "nM" tag that STAR added, and tried running with a defined read length equal to the sum of both reads (to account for nM's meaning).

### What I Did

```
spladder build --parallel 8 \
  --annotation ~/RAWDATA/ucsc_hg19.gtf \
  --bams A.bam,B.bam \
  --readlen 152 -o randomSamples.spladder 1> build.out 2> build.err
```

Which resulted in:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/spladder/spladder.py", line 335, in main
    spladder(argv)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/spladder/spladder.py", line 160, in spladder
    genes = cPickle.load(open(CFG['anno_fname'], 'r'))
ValueError: unsupported pickle protocol: 4
```

A little googling suggests this is just fixed in python3. Which would lead me back to Issue #71. Is there anything I can do to fix this pickle problem in the meantime, though?

Thanks,
~Joe

**Comment by jfass** [comment]
Ah! So apparently the protocol is just a version of the pickle file format. And pickle 4 was added in python3. So why would there be an inconsistency when I'm just using an older version of spladder, which presumably be self-consistent in use of an older format? Turns out there was a pickle file corresponding to the annotation, left from the last time I ran spladder 2.something. So I removed that .pickle file and spladder's running fine now.
