### ISSUE TITLE
"All result files already exist" and "UnboundLocalError: local variable 'fn_in_count' referenced before assignment"

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#92]
* spladder version: 2.2.1
* Python version: 3.5.2
* Operating System: Ubuntu 14.04

### Description

When running 'spladder build --qmode collect', I'm seeing the line:
```
outdir/spladder/genes_graph_conf0.{sample name}.pickle - All result files already exist
```
show up in STDOUT. Also, I'm seeing:
```
Traceback (most recent call last):
  File "/home/ubuntu/spladder/spladder-venv/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/spladder/spladder-venv/lib/python3.5/site-packages/spladder/spladder.py", line 192, in main
    options.func(options)
  File "/home/ubuntu/spladder/spladder-venv/lib/python3.5/site-packages/spladder/spladder_build.py", line 237, in spladder
    count_graph_coverage_wrapper(fn_in_count, fn_out_count, options)
UnboundLocalError: local variable 'fn_in_count' referenced before assignment
```
show up in STDERR.

### What I Did

```
spladder build --bams ${B1},${B2},${B3} --annotation chr7.temp.gtf --outdir ${S1}.${S2}.${S3}.%.spladder --set-mm-tag nM --readlen 150 --merge-all merge_graphs --extract-ase --quantify-graph --qmode collect 1> quant.chr7.out 2> quant.chr7.out
```

### Edit - outcome

No quantification was done, and no new files (like .txt.gz files) were created above the spladder directory.

**Comment by jfass** [comment]
This seems to have been caused by adding --qmode collect to the previous command, without having run quantification. The command that is now running (instead of failing immediately, as above) has "--merge-strat merge_graphs" (like the previous merge step that merged individual samples run with --merge-strat single) but adding "--qmode all".

So, separately:

```
spladder build --bams bam1 --annotation ann.gtf --outdir out --merge-strat single --no-extract-ase --no-quantify-graph
spladder build --bams bam2 --annotation ann.gtf --outdir out ... [same as above]
```

Then:

```
spladder build --bams bam1,bam2,etc. --annotation ann.gtf --outdir out --merge-strat merge_graphs --no-extract-ase --no-quantify-graph
```

And finally:

```
spladder build --bams bam1,bam2,etc. --annotation ann.gtf --outdir out --merge-strat merge_graphs --extract-ase --quantify-graph --qmode all
```

This is running currently, so I'm going to close this Issue and report back if there are more problems.
