### ISSUE TITLE
spladder viz fails. TypeError Indexing

### ISSUE THREAD

**Issue by Alex-Nesta** [ratschlab/spladder#94]
* spladder version: 2.2.2
* Python version: 3.7.3
* Operating System: Linux Cluster 2.6.32-754.3.5.el6.x86_64

### Description

Describe what you were trying to get done.

I am trying to visualize my results using spladder viz

Tell us what happened, what went wrong, and what you expected to happen.

I got an error message.
It looks like the hdf5 file order is not sorted properly?
I was expecting a folder of plots to be created. 

### What I Did

```
spladder.log

(TCGA_spladder-env) [nestaa@helix logs]$ less viz_samples.log 

get segment counts


--------------------------------------------------------------------------------
|  JAX TORQUE EPILOGUE
|
|  Job ID: 10485182.helix-master
|  Exit Status: 1
|  Requested Resources:
|      nodes=1:ppn=1,walltime=28:00:00
|  Resources Consumed:
|      cput=00:00:20,mem=2922372kb,vmem=5540772kb,walltime=00:00:24
|  Walltime accuracy: 0.0%
|
| Epilogue Host (TORQUE Mother Superior): helix035
|
--------------------------------------------------------------------------------

```

```
spladder.err

(TCGA_spladder-env) [nestaa@helix logs]$ less viz_samples.err 

Traceback (most recent call last):
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: only size-1 arrays can be converted to Python scalars

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/spladder/spladder.py", line 195, in main
    options.func(options)
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/spladder/spladder_viz.py", line 199, in spladder_viz
    _plot_segments(options, gid, fig, axes, gs)
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/spladder/spladder_viz.py", line 300, in _plot_segments
    (segments, edges, edge_idx, strains) = get_seg_counts(options, gid[0])
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/spladder/helpers_viz.py", line 147, in get_seg_counts
    edges = IN['edges'][idx, :]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/nestaa/miniconda/envs/TCGA_spladder-env/lib/python3.7/site-packages/h5py/_hl/selections.py", line 367, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
viz_samples.err (END) 
```
```
#!/bin/bash

#PBS -q batch
#PBS -l walltime=28:00:00
#PBS -l nodes=1:ppn=1
#PBS -e /projects/beck-lab/alex/Breast_Cancer/scripts/spladder/logs/viz_samples.err
#PBS -o /projects/beck-lab/alex/Breast_Cancer/scripts/spladder/logs/viz_samples.log

module load libpng
source activate TCGA_spladder-env


HMEC="/projects/beck-lab/alex/Breast_Cancer/scripts/HMEC/shortread/samtobamout/hg38XYM/HMEC_hg38XYM_hisat2_sorted_chrfix.bam"
HS578BST="/projects/beck-lab/alex/Breast_Cancer/scripts/HS578BST/shortread/samtobamout/hg38XYM/HS578BST_hg38XYM_hisat2_sorted_chrfix.bam"
MCF10JGM="/projects/beck-lab/alex/Breast_Cancer/scripts/MCF10JGM/shortread/samtobamout/hg38XYM/MCF10JGM_hg38XYM_hisat2_sorted_chrfix.bam"
NBT1="/projects/beck-lab/alex/Breast_Cancer/scripts/NBT1/shortread/samtobamout/hg38XYM/NBT1_hg38XYM_hisat2_sorted_chrfix.bam"
MCF7JGM="/projects/beck-lab/alex/Breast_Cancer/scripts/MCF7JGM/shortread/samtobamout/hg38XYM/MCF7JGM_hg38XYM_hisat2_sorted_chrfix.bam"
HS578T="/projects/beck-lab/alex/Breast_Cancer/scripts/HS578T/shortread/samtobamout/hg38XYM/HS578T_hg38XYM_hisat2_sorted_chrfix.bam"

outdir_b="/projects/beck-lab/alex/Breast_Cancer/scripts/spladder"
#annotation="/projects/beck-lab/alex/Breast_Cancer/scripts/chaining/MCF7TNBCandNormal/gffcmp.exonannotated2.gtf"

spladder viz \
    -o $outdir_b

viz_samples.pbs (END) 

```

**Comment by akahles** [comment]
Dear @Alex-Nesta,
thanks for reporting this issue. I am currently working on re-structuring the visualisation part. I will post here once this has happened. This should make the plotting more robust in general and should hopefully also get rid of this issue.
Best,
Andre

**Comment by akahles** [comment]
I have rewritten the visualisation part of SplAdder for the latest release. Please refer to the online documentation (https://spladder.readthedocs.io/en/latest/) for further information. Please open a new issue in case further arise.
